import {renderCover as art} from './assets/post-cover.js';
import {loadLivePosts,mergePosts} from './assets/live-posts.js';
import {renderBlock} from './assets/post-content.js';
import {mountViewCounter} from './view-counter.js';
import {mountComments,mountCommunity,mountAdmin,mountWrite,initializeIdentity} from './community.js';
import {escapeHTML as esc,youtubeId,safeImage} from './assets/helpers.js';
const $=s=>document.querySelector(s);let posts=[],category='All',query='';
const readStorage=key=>{try{return localStorage.getItem(key)}catch{return null}};
if(readStorage('theme')==='dark')document.body.classList.add('dark');
$('#theme-toggle').onclick=()=>{document.body.classList.toggle('dark');try{localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light')}catch{}};
const date=p=>esc(p.date.replaceAll('-','.'));
const meta=p=>`<div class="meta"><span>${date(p)}</span><span>·</span><span>${p.minutes||5} min read</span></div>`;
const tags=p=>`<div class="tags">${(p.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>`;
function card(p){return `<a class="card" href="posts/${encodeURIComponent(p.id)}/">${art(p)}<div class="post-category">${esc(p.category)} <span class="pill">${p.sample?'SAMPLE':'ARTICLE'}</span></div><h3>${esc(p.title)}</h3><p class="excerpt">${esc(p.excerpt)}</p>${meta(p)}${tags(p)}</a>`}
function home(){const p=posts[0];$('#main').innerHTML=`<section class="hero"><div><div class="eyebrow"><span class="tiny-square"></span> A DEVELOPER’S PERSONAL JOURNAL</div><h1>Less talk<span>,</span><br>more <span style="color:var(--ink)">log.</span></h1><p class="hero-desc"><strong>배우고, 기록하고, 나눕니다.</strong><br>어제보다 조금 더 나은 코드를 위한, 느긋하지만 꾸준한 기록.</p></div><aside class="profile"><div class="profile-top"><img class="avatar" src="assets/avatar.svg" alt="안경을 쓴 부잉의 프로필 일러스트"><div><div class="profile-name">안녕하세요, 부잉입니다.</div><div class="profile-status">Developer & lifelong learner</div></div></div><p>귀찮은 건 줄이고,<br>좋은 건 함께 나누고 싶은 개발자.</p><a class="profile-link" href="about/">조금 더 알아보기 <span>↗</span></a><div class="profile-views" data-view-counter title="누적 방문 세션 수입니다. 같은 브라우저에서는 마지막 접속 후 30분 동안 한 번만 집계하며, 숫자는 다음 세션에 갱신됩니다.">누적 조회수 · 불러오는 중</div></aside></section>${p?`<section><div class="section-heading"><h2>THE FEATURED POST</h2><span class="index">01 / EDITOR’S PICK</span></div><a class="featured" href="posts/${encodeURIComponent(p.id)}/">${art(p)}<div class="featured-content"><div class="post-category">${esc(p.category)} <span class="pill">${p.sample?'SAMPLE POST':'FEATURED'}</span></div><h2>${esc(p.title)}</h2><p class="excerpt">${esc(p.excerpt)}</p><div class="meta"><span>${date(p)}</span><span>·</span><span>${p.minutes||5} min read</span><span class="read-arrow">↗</span></div></div></a></section>`:''}<section class="journal"><div class="journal-top"><div class="journal-title"><h2>Latest records<span style="color:var(--muted)">.</span></h2><span class="count">${String(posts.length).padStart(2,'0')}</span></div><span class="view-note">작은 발견이 쌓여, 더 나은 내일이 됩니다.</span></div><div class="filter-bar"><div class="filters">${['All','Development','Dev Notes','Tutorial'].map(c=>`<button class="filter ${c===category?'active':''}" data-category="${c}" aria-pressed="${c===category}">${c==='All'?'전체':c}<sup>${c==='All'?posts.length:posts.filter(p=>p.category===c).length}</sup></button>`).join('')}</div><label class="inline-search"><input id="list-search" placeholder="기록 속에서 찾기" aria-label="게시글 검색" value="${esc(query)}"><span>⌕</span></label></div><div class="post-grid" id="post-grid"></div><div class="journal-bottom">YOU’RE ALL CAUGHT UP. KEEP LEARNING ↗</div></section>`;renderCards();document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});renderCards()});$('#list-search').oninput=e=>{query=e.target.value;renderCards()};}
function matches(p,q){return `${p.title} ${p.excerpt} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(q.toLowerCase())}
function renderCards(){const filtered=posts.filter(p=>(category==='All'||p.category===category)&&matches(p,query));$('#post-grid').innerHTML=filtered.length?filtered.map(card).join(''):'<p class="empty">일치하는 기록이 없습니다. 다른 검색어로 찾아보세요.</p>'}
const block=renderBlock;
function article(id){const p=posts.find(p=>p.id===id);if(!p){$('#main').innerHTML='<section class="article"><h1>기록을 찾을 수 없습니다.</h1><a href="./">← 글 목록으로</a></section>';return;}document.title=`${p.title} — BUIING`;$('#main').innerHTML=`<article class="article"><a href="./" class="back-link">← 모든 기록으로 돌아가기</a><div class="post-category">${esc(p.category)} ${p.sample?'<span class="pill">SAMPLE POST</span>':''}</div><h1>${esc(p.title)}</h1><a class="outline-btn owner-edit" href="write/?edit=${encodeURIComponent(p.id)}" hidden>게시글 수정 ↗</a>${meta(p)}${art(p)}<div class="article-body">${p.blocks.map(block).join('')}</div>${tags(p)}<section id="comments" class="discussion-section"></section><div style="margin-top:45px;border-top:1px solid var(--line);padding-top:25px"><a href="./">← 다음 배움을 찾아보기</a></div></article>`}
function about(){$('#main').innerHTML=`<section class="about"><div class="about-top"><span class="eyebrow">BEHIND THE RECORDS</span><img src="assets/avatar.svg" class="avatar" alt="부잉 프로필"></div><h1>Stay curious.<br>Keep it simple.</h1><p>안녕하세요, 부잉입니다.<br>귀찮은 일을 줄이기 위해 코드를 쓰고,<br>다시 헤매지 않기 위해 배운 것을 기록합니다.</p><p>이곳은 개발하며 마주친 문제와 해결 과정, 새롭게 배운 개념,<br>그리고 누군가에게 도움이 되었으면 하는 지식을 나누는 공간입니다.</p><div class="about-list"><div><strong>01 — Development</strong><span>코드 속에서 발견한 더 나은 방법</span></div><div><strong>02 — Dev Notes</strong><span>잊기 전에 적어두는 작은 배움</span></div><div><strong>03 — Tutorial</strong><span>함께 따라 하며 이해하는 개발</span></div></div><a class="profile-link" style="margin-top:35px" href="./">기록 읽으러 가기 <span>↗</span></a></section>`}
function route(){const base=new URL(document.baseURI).pathname;const path=location.pathname.startsWith(base)?location.pathname.slice(base.length):location.pathname.slice(1);const legacy=location.hash;if(legacy.startsWith('#post/')){location.replace(new URL('posts/'+encodeURIComponent(decodeURIComponent(legacy.slice(6)))+'/',document.baseURI));return}if(legacy==='#about'){location.replace(new URL('about/',document.baseURI));return}document.querySelectorAll('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.nav===(path.startsWith('about')?'about':path.startsWith('community')?'community':path.startsWith('write')?'write':path.startsWith('admin')?'admin':'home')));if(path.startsWith('posts/')){let id;try{id=decodeURIComponent(path.split('/')[1])}catch{id=''}article(id);void mountComments(id)}else if(path.startsWith('about'))about();else if(path.startsWith('community'))void mountCommunity();else if(path.startsWith('admin'))void mountAdmin();else if(path.startsWith('write'))void mountWrite();else if(!path||path==='index.html')home();else $('#main').innerHTML='<section class="article"><h1>페이지를 찾을 수 없습니다.</h1><a href="./">홈으로 돌아가기</a></section>';mountViewCounter();}
window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#post/')||location.hash==='#about')route()});
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
$('#search-toggle').onclick=()=>{$('#search-dialog').showModal();$('#global-search').focus();search()};
function search(){const q=$('#global-search').value.trim();const results=posts.filter(p=>matches(p,q));$('#search-results').innerHTML=results.length?results.map(p=>`<a class="search-result" href="posts/${encodeURIComponent(p.id)}/"><small>${esc(p.category)}</small>${esc(p.title)} ↗</a>`).join(''):'<p class="empty">검색 결과가 없습니다.</p>';document.querySelectorAll('.search-result').forEach(a=>a.onclick=()=>$('#search-dialog').close())}$('#global-search').oninput=search;
void initializeIdentity();
try{const [snapshot,live]=await Promise.all([fetch('./posts.json').then(async r=>r.ok?await r.json():null).catch(()=>null),loadLivePosts()]);if(!snapshot&&!live.length)throw Error('load');posts=mergePosts(snapshot||[],live);route()}catch{if(!$('#main').textContent.trim())$('#main').innerHTML='<section class="article"><h1>기록을 불러오지 못했습니다.</h1><p>새로고침해 주세요.</p></section>'}

void initializeIdentity();
