import {escapeHTML as esc,youtubeId,safeImage,parseText} from './assets/helpers.js';
const markup="<dialog id=\"editor-dialog\"><div class=\"dialog-head\"><div><span class=\"eyebrow\">NEW RECORD</span><h2>오늘의 배움을 남겨보세요.</h2></div><button class=\"icon-btn close-dialog\" aria-label=\"닫기\">✕</button></div><p class=\"editor-note\">브라우저에 초안을 저장하고, 완성된 글 파일을 저장소의 posts 폴더에 추가하세요.</p><form id=\"editor\"><input id=\"edit-title\" placeholder=\"글 제목\" required maxlength=\"160\" aria-label=\"글 제목\"><div class=\"editor-row\"><select id=\"edit-category\" aria-label=\"카테고리\"><option>Development</option><option>Dev Notes</option><option>Tutorial</option></select><input id=\"edit-tags\" placeholder=\"태그 (쉼표로 구분)\" aria-label=\"태그\"></div><textarea id=\"edit-text\" rows=\"9\" placeholder=\"새롭게 배운 것들을 적어주세요. 빈 줄은 문단 구분, ## 은 소제목, ``` 은 코드 블록입니다.\" aria-label=\"본문\"></textarea><div class=\"media-toolbar\"><label class=\"outline-btn\">＋ 이미지 / GIF<input id=\"image-upload\" type=\"file\" accept=\"image/png,image/jpeg,image/webp,image/gif\" multiple hidden></label><button class=\"outline-btn\" type=\"button\" id=\"add-video\">＋ YouTube</button></div><div id=\"video-entry\" hidden><input id=\"youtube-url\" type=\"url\" placeholder=\"https://www.youtube.com/watch?v=...\" aria-label=\"YouTube URL\"><button type=\"button\" class=\"outline-btn\" id=\"confirm-video\">영상 추가</button></div><div id=\"media-preview\"></div><p id=\"editor-status\" role=\"status\"></p><div class=\"editor-bottom\"><button class=\"outline-btn\" type=\"button\" id=\"save-draft\">초안 저장</button><button class=\"black-btn\" type=\"submit\">글 파일 다운로드 ↗</button></div></form></dialog>";
export function mountBlogEditor({authorize,onDenied,userId}) {
  document.querySelector('#editor-dialog')?.remove();
  document.body.insertAdjacentHTML('beforeend',markup);
  const $=s=>document.querySelector(s);
  const draftKey='buiing-admin-draft:'+userId;
  const readStorage=key=>{try{return localStorage.getItem(key)}catch{return null}};
  let media=[];
  const guard=async()=>{if(await authorize())return true;document.querySelector('#editor-dialog')?.remove();await onDenied();return false;};
  $('#editor-dialog .close-dialog').onclick=()=>$('#editor-dialog').close();
const status=message=>{if($('#editor-status'))$('#editor-status').textContent=message};
function draft(){return {title:$('#edit-title').value,category:$('#edit-category').value,tags:$('#edit-tags').value,text:$('#edit-text').value,media}}
const openEditor=async()=>{if(!await guard())return;$('#editor-dialog').showModal();if(!$('#edit-title').value){try{const d=JSON.parse(readStorage(draftKey));if(d){$('#edit-title').value=d.title||'';$('#edit-category').value=d.category||'Development';$('#edit-tags').value=d.tags||'';$('#edit-text').value=d.text||'';media=Array.isArray(d.media)?d.media:[];renderMedia();status('저장된 초안을 불러왔습니다.')}}catch{status('초안을 불러오지 못했습니다.')}}};
$('#save-draft').onclick=async()=>{if(!await guard())return;try{localStorage.setItem(draftKey,JSON.stringify(draft()));status('이 브라우저에 초안을 저장했습니다.')}catch{status('저장 공간이 부족합니다. 글 파일을 다운로드해 보관하세요.')}};
function renderMedia(){if(!$('#media-preview'))return;$('#media-preview').innerHTML=media.map((m,i)=>`<div class="media-item">${m.type==='image'?`<img src="${esc(safeImage(m.src))}" alt="첨부 미리보기"><span>${esc(m.alt)}</span>`:`<span>▶ YouTube · ${esc(youtubeId(m.url))}</span>`}<button type="button" data-remove="${i}" aria-label="첨부 삭제">✕</button></div>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{media.splice(Number(b.dataset.remove),1);renderMedia()})}
$('#image-upload').onchange=async e=>{for(const file of e.target.files){if(!['image/png','image/jpeg','image/gif','image/webp'].includes(file.type)){status('PNG, JPG, WebP, GIF 이미지를 선택하세요.');continue}if(file.size>10*1024*1024){status('이미지는 파일당 10MB 이하로 첨부하세요.');continue}try{const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});media.push({type:'image',src,alt:file.name});}catch{status('이미지를 읽지 못했습니다. 다시 첨부하세요.')}}renderMedia();e.target.value=''};
$('#add-video').onclick=()=>{$('#video-entry').hidden=!$('#video-entry').hidden;if(!$('#video-entry').hidden)$('#youtube-url').focus()};$('#confirm-video').onclick=()=>{const url=$('#youtube-url').value.trim();if(!youtubeId(url)){status('올바른 YouTube 영상 URL을 입력하세요.');return}media.push({type:'youtube',url});renderMedia();$('#youtube-url').value='';$('#video-entry').hidden=true;status('영상을 추가했습니다.')};
$('#editor').onsubmit=async e=>{e.preventDefault();if(!await guard())return;const d=draft();if(!d.title.trim()||(!d.text.trim()&&!media.length)){status('제목과 본문 또는 첨부를 입력하세요.');return}const p={id:crypto.randomUUID(),title:d.title.trim(),category:d.category,tags:d.tags.split(',').map(t=>t.trim()).filter(Boolean),date:new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date()),excerpt:d.text.trim().slice(0,130),minutes:Math.max(1,Math.ceil(d.text.length/500)),art:'code',blocks:[...parseText(d.text),...media]};const blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${p.date}-${p.id.slice(0,8)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('글 파일을 다운로드했습니다. GitHub 저장소의 posts 폴더에 추가하면 배포 시 공개됩니다.');};

  const launch=document.querySelector('#admin-write-button');
  if(launch)launch.onclick=openEditor;
  if(new URLSearchParams(location.search).get('compose')==='1')void openEditor();
}
