import {codeLanguages,codeLanguage,highlightCode} from './assets/code-content.js';
import {linkDetails,safeLink} from './assets/links.js';
import {moveBlock} from './assets/block-order.js';
import {renderCover,defaultTerminalText,coverDesigns} from './assets/post-cover.js';
import {escapeHTML as esc,youtubeId,parseText} from './assets/helpers.js';
import {renderBlock} from './assets/post-content.js';
import {draftStore} from './assets/drafts.js';
const blank=()=>({id:'',title:'',category:'Development',tags:'',art:'code',blocks:[{type:'paragraph',text:''}]});
const messages={INVALID_BLOCK:'지원하지 않는 블록입니다. 기존 게시 함수가 설치돼 있다면 publish-post를 최신 코드로 업데이트해 주세요.',INVALID_LINK:'올바른 HTTP / HTTPS 링크와 표시 방식을 선택해 주세요.',EDIT_CONFLICT:'다른 곳에서 수정된 글입니다. 초안을 저장한 뒤 최신 게시글을 다시 열어 주세요.',PUBLISH_SETUP_REQUIRED:'게시 연결 설정이 필요합니다. 운영자 설치 안내의 publish-post 설정을 완료해 주세요.',GITHUB_ACCESS_FAILED:'GitHub 연결 권한을 확인해 주세요.',GITHUB_WRITE_FAILED:'GitHub 글 저장에 실패했습니다. 토큰의 Contents 쓰기 권한과 만료일을 확인해 주세요.',FORBIDDEN:'운영자만 게시할 수 있습니다.',LOGIN_REQUIRED:'로그인이 만료됐습니다. 다시 로그인해 주세요.'};
export async function mountBlogEditor({authorize,onDenied,userId,client}){
 const host=document.querySelector('#write-content');
 host.innerHTML=`<section id="editor-dialog" class="write-editor"><div class="dialog-head"><div><span class="eyebrow">WRITE / EDIT</span><h1>기록을 남기세요.</h1></div><a class="outline-btn" href="admin/">관리자 ↗</a></div>
 <details id="draft-panel"><summary>임시저장 목록 <span id="draft-count">0</span></summary><p class="editor-note">이 계정 · 현재 브라우저에 저장됩니다. 브라우저 데이터를 삭제하면 초안도 삭제됩니다.</p><div id="draft-list"></div></details>
 <div class="draft-settings"><label><input id="auto-save" type="checkbox"> 자동 임시저장</label><label>저장 주기 <select id="save-interval"><option value="5">5초</option><option value="15">15초</option><option value="30">30초</option><option value="60">1분</option><option value="300">5분</option></select></label><button id="new-post" class="outline-btn">새 글</button></div>
 <p id="draft-current" class="editor-note">새 글 · 아직 저장하지 않았습니다.</p>
 <form id="editor" hidden><input id="edit-title" placeholder="글 제목" required maxlength="160" aria-label="글 제목"><div class="editor-row"><select id="edit-category" aria-label="카테고리"><option>Development</option><option>Dev Notes</option><option>Tutorial</option></select><input id="edit-tags" placeholder="태그 (쉼표로 구분)" aria-label="태그"></div>
 <fieldset class="cover-settings"><legend>게시글 썸네일</legend><p class="editor-note">메인 추천 글 · 글 목록 · 게시글 상단에 같은 썸네일이 표시됩니다.</p><input type="hidden" id="edit-art"><details id="cover-picker"><summary id="cover-picker-summary">기본 디자인 선택 <span id="cover-selection-name"></span> ▾</summary><div id="cover-options" role="listbox" aria-label="썸네일 기본 디자인">${coverDesigns.map(d=>`<button type="button" role="option" data-cover-type="${d.id}" aria-selected="false"><span class="cover-option-art">${renderCover({art:d.id})}</span><strong>${esc(d.name)}</strong></button>`).join('')}</div></details><div class="editor-row"><label>상단 문구<input id="edit-art-label" maxlength="120" placeholder="기본 문구 사용"></label><label>하단 문구<input id="edit-art-caption" maxlength="120" placeholder="기본 문구 사용"></label></div><div id="cover-center-controls"><label><span id="cover-center-label">중앙 내용</span><textarea id="edit-art-center" rows="4" aria-label="썸네일 중앙 내용"></textarea></label><button type="button" id="reset-cover-text" class="outline-btn">중앙 내용 기본값 복원</button></div><label>썸네일 이미지 URL<input type="url" id="cover-url" placeholder="https://example.com/image.png"></label><div class="cover-actions"><button type="button" id="apply-cover-url" class="outline-btn">이미지 URL 적용</button><button type="button" id="choose-cover" class="outline-btn">썸네일 이미지 업로드</button><button type="button" id="remove-cover" class="outline-btn" hidden>이미지 삭제 · 기본 디자인 사용</button></div><input type="file" id="cover-upload" accept="image/png,image/jpeg,image/webp,image/gif" hidden><label id="cover-alt-label" hidden>이미지 설명<input id="edit-cover-alt" maxlength="500"></label><div id="cover-preview"></div></fieldset>
 <div class="markdown-guide"><button type="button" id="markdown-help-toggle" class="help-bubble" aria-label="마크다운 도움말" aria-expanded="false" aria-controls="markdown-help">?</button><span>본문에서 마크다운을 사용할 수 있습니다.</span><div id="markdown-help" class="markdown-tooltip" role="region" aria-label="마크다운 작성 방법" hidden><h3>마크다운 빠른 안내</h3><dl><dt>제목</dt><dd><code># 큰 제목</code> · <code>## 소제목</code></dd><dt>강조</dt><dd><code>**굵게**</code> · <code>*기울임*</code> · <code>~~취소선~~</code></dd><dt>링크 / 이미지</dt><dd><code>[문구](https://주소)</code> · <code>![설명](https://이미지주소)</code></dd><dt>목록 / 인용</dt><dd><code>- 항목</code> · <code>1. 항목</code> · <code>&gt; 인용문</code></dd><dt>코드</dt><dd><code>\`짧은 코드\`</code> · 세 개의 백틱으로 여러 줄 코드 감싸기</dd><dt>표 / 구분선</dt><dd><code>| 제목 | 제목 |</code> 다음 줄에 <code>| --- | --- |</code> · <code>---</code></dd></dl><p>본문에서 마크다운을 그대로 쓰면 됩니다. Shift+Enter로 줄을 바꿔 목록·표를 작성하세요. 여러 줄 코드는 코드 블록을 선택하고 언어를 지정할 수 있습니다. HTML 코드는 실행되지 않습니다.</p></div></div><p class="editor-note">Enter: 새 문단 · Shift+Enter: 줄바꿈. 이미지/GIF를 문단 사이에 끌어놓거나 링크 주소를 붙여넣으세요.</p><div id="content-blocks"></div><input id="image-upload" type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple hidden>
 <div class="editor-bottom"><button class="outline-btn" id="preview-post" type="button">미리보기</button><button class="outline-btn" id="save-draft" type="button" disabled>임시저장</button><button class="black-btn" id="publish-post" type="submit">포스트 게시 ↗</button></div></form><p id="editor-status" role="status"></p><div id="publish-result"></div>
 <dialog id="body-image-choice"><div class="dialog-head"><h2>이미지 삽입</h2><button type="button" id="body-image-cancel" aria-label="취소">✕</button></div><button type="button" id="choose-body-image" class="outline-btn">이미지 파일 업로드</button><label>이미지 URL<input type="url" id="body-image-url" placeholder="https://example.com/image.png"></label><label>이미지 설명<input id="body-image-alt" maxlength="500"></label><p id="body-image-error" role="status"></p><button type="button" id="insert-body-image" class="black-btn">URL 이미지 삽입</button></dialog>
 <dialog id="youtube-choice"><div class="dialog-head"><h2>링크 표시 방식</h2><button type="button" id="video-cancel" aria-label="취소">✕</button></div><label>주소<input id="youtube-url" type="url" placeholder="https://example.com"></label><label>표시 제목<input id="youtube-title" maxlength="160" placeholder="링크 제목"></label><label>북마크 설명<input id="link-description" maxlength="500" placeholder="설명 (선택)"></label><label>북마크 썸네일 URL<input id="link-thumbnail" type="url" placeholder="https://… (선택)"></label><p class="editor-note">제목·설명·썸네일을 지정할 수 있습니다. 일반 링크는 사이트 이름으로 표시되며, YouTube는 영상 썸네일을 사용합니다.</p><label>형식<select id="youtube-mode"><option value="embed">임베드 · 본문에 표시</option><option value="url">URL · 주소 그대로</option><option value="mention">멘션 · 짧은 링크</option><option value="bookmark">북마크 · 썸네일 카드</option></select></label><p id="video-error" role="status"></p><button id="confirm-video" class="black-btn">본문에 삽입</button></dialog>
 <dialog id="post-preview"><div class="dialog-head"><h2>게시글 미리보기</h2><button id="close-preview" aria-label="미리보기 닫기">✕</button></div><article class="article"><h1 id="preview-title"></h1><div id="preview-cover"></div><div id="preview-body" class="article-body"></div></article></dialog></section>`;
 const $=s=>host.querySelector(s),prefKey='buiing-draft-options:'+userId;
 let dragging=null;const dragToken=crypto.randomUUID();
 let doc=blank(),draftId=crypto.randomUUID(),file=null,sha=null,lastSaved='',timer=null,saving=false,publishing=false,dirty=false,active=true,loading=true,loadFailed=false,uploadIndex=0,videoInsertion=null,pollTimer=null;
 let prefs={auto:true,interval:30};try{prefs={...prefs,...JSON.parse(localStorage.getItem(prefKey)||'{}')}}catch{}
 if(![5,15,30,60,300].includes(Number(prefs.interval)))prefs.interval=30;
 $('#auto-save').checked=!!prefs.auto;$('#save-interval').value=String(prefs.interval);
 const status=text=>{if(active&&$('#editor-status'))$('#editor-status').textContent=text};
 const serialize=()=>JSON.stringify({doc,file,sha});
 const key=id=>userId+'/'+id;
 const guard=async()=>{if(await authorize())return true;active=false;clearTimeout(timer);clearTimeout(pollTimer);await onDenied();return false};
 const persistPrefs=()=>{prefs={auto:$('#auto-save').checked,interval:Number($('#save-interval').value)};try{localStorage.setItem(prefKey,JSON.stringify(prefs))}catch{}clearTimeout(timer);timer=null;updateDirty()};
 $('#auto-save').onchange=$('#save-interval').onchange=persistPrefs;
 function updateDirty(){if(!active)return;dirty=serialize()!==lastSaved;$('#save-draft').disabled=!dirty||saving||publishing;if(!dirty){clearTimeout(timer);timer=null}else if(prefs.auto&&!timer&&!saving&&!publishing)timer=setTimeout(()=>{timer=null;void save()},prefs.interval*1000)}
 async function save(){if(!dirty||saving||publishing||!active)return;clearTimeout(timer);timer=null;saving=true;updateDirty();const snapshot=serialize(),id=draftId;try{const value={owner:userId,id,savedAt:new Date().toISOString(),...JSON.parse(snapshot)};await draftStore.put(key(id),value);if(active&&id===draftId){lastSaved=snapshot;$('#draft-current').textContent='현재 초안: '+(value.doc.title||'제목 없는 글')+' · '+new Date(value.savedAt).toLocaleString('ko-KR');status('임시저장했습니다.');await listDrafts()}}catch{status('임시저장하지 못했습니다. 브라우저 저장 공간과 설정을 확인해 주세요.')}finally{saving=false;updateDirty()}}
 $('#save-draft').onclick=async()=>{if(await guard())await save()};
 const changed=()=>{updateDirty();$('#publish-result').replaceChildren()};
 function render(){ $('#edit-title').value=doc.title;$('#edit-category').value=doc.category;$('#edit-tags').value=doc.tags;$('#publish-post').textContent=file?'수정 사항 게시 ↗':'포스트 게시 ↗';renderCoverSettings();renderBlocks(); }
 function setDocument(value,id=crypto.randomUUID()){loadFailed=false;clearTimeout(pollTimer);$('#publish-result').replaceChildren();clearTimeout(timer);timer=null;doc=structuredClone(value.doc||blank());doc.blocks=doc.blocks.map(b=>b.type==='markdown'?{...b,type:'paragraph'}:b);draftId=id;file=value.file||null;sha=value.sha||null;lastSaved=serialize();render();$('#publish-post').disabled=false;updateDirty()}
 $('#markdown-help-toggle').onclick=()=>{const expanded=$('#markdown-help-toggle').getAttribute('aria-expanded')==='true';$('#markdown-help-toggle').setAttribute('aria-expanded',String(!expanded));$('#markdown-help').hidden=expanded};
 $('#markdown-help-toggle').onkeydown=e=>{if(e.key==='Escape'){$('#markdown-help').hidden=true;e.target.setAttribute('aria-expanded','false')}};
 function renderCoverSettings(){
  $('#edit-art').value=doc.art||'code';$('#edit-art-label').value=doc.artLabel??'';$('#edit-art-caption').value=doc.artCaption??'';$('#edit-cover-alt').value=doc.coverAlt||'';$('#cover-url').value=doc.coverImage?.startsWith('https://')?doc.coverImage:'';$('#cover-selection-name').textContent=coverDesigns.find(d=>d.id===(doc.art||'code'))?.name||'코드';host.querySelectorAll('[data-cover-type]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.coverType===(doc.art||'code'))));updateCenterControls();updateCoverPreview();
 }
 const centerField=()=>doc.art==='terminal'?'artTerminalText':(doc.art||'code')==='code'?'artCodeText':'artText';
 function updateCenterControls(){const type=doc.art||'code',terminal=type==='terminal';$('#cover-center-controls').hidden=!!doc.coverImage||['layers','orb'].includes(type);$('#cover-center-label').textContent=terminal?'터미널 본문 · 줄바꿈 가능':type==='code'?'괄호 안 문자 / 문구':'중앙 문구';$('#edit-art-center').maxLength=terminal?1000:type==='code'?80:300;$('#edit-art-center').value=doc[centerField()]??(terminal?defaultTerminalText:coverDesigns.find(d=>d.id===type)?.text||'');$('#edit-art-center').rows=terminal?6:2}
 $('#edit-art-center').oninput=e=>{doc[centerField()]=e.target.value;updateCoverPreview();changed()};
 $('#reset-cover-text').onclick=()=>{delete doc[centerField()];updateCenterControls();updateCoverPreview();changed()};
 host.querySelectorAll('[data-cover-type]').forEach(b=>b.onclick=()=>{doc.art=b.dataset.coverType;delete doc.coverImage;delete doc.coverAlt;$('#cover-picker').open=false;renderCoverSettings();changed()});
 $('#cover-options').onkeydown=e=>{const buttons=[...host.querySelectorAll('[data-cover-type]')],index=buttons.indexOf(document.activeElement);if(e.key==='Escape'){$('#cover-picker').open=false;$('#cover-picker-summary').focus();return}const columns=matchMedia('(max-width:640px)').matches?2:3;const delta={ArrowRight:1,ArrowLeft:-1,ArrowDown:columns,ArrowUp:-columns}[e.key];if(delta){e.preventDefault();buttons[(index+delta+buttons.length)%buttons.length].focus()}};
 $('#apply-cover-url').onclick=()=>{const value=safeLink($('#cover-url').value);if(!value||!value.startsWith('https://')){status('HTTPS 이미지 주소를 입력해 주세요.');return}doc.coverImage=value;renderCoverSettings();changed()};

 function updateCoverPreview(){const image=!!doc.coverImage;$('#remove-cover').hidden=$('#cover-alt-label').hidden=!image;for(const id of ['#edit-art-label','#edit-art-caption'])$(id).disabled=image;$('#cover-preview').innerHTML=renderCover(doc)}
 for(const [id,field] of [['#edit-art','art'],['#edit-art-label','artLabel'],['#edit-art-caption','artCaption'],['#edit-cover-alt','coverAlt']])$(id).oninput=e=>{if(field==='artLabel'||field==='artCaption'){if(e.target.value)doc[field]=e.target.value;else delete doc[field]}else doc[field]=e.target.value;if(field==='art')updateCenterControls();updateCoverPreview();changed()};
 $('#choose-cover').onclick=()=>$('#cover-upload').click();
 $('#remove-cover').onclick=()=>{delete doc.coverImage;delete doc.coverAlt;renderCoverSettings();changed()};
 $('#cover-upload').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;if(!['image/png','image/jpeg','image/webp','image/gif'].includes(f.type)||f.size>10485760){status('PNG/JPG/WebP/GIF, 10MB 이하의 썸네일만 사용할 수 있습니다.');return}const current=draftId;try{const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)});if(!active||current!==draftId)return;doc.coverImage=src;doc.coverAlt=f.name;renderCoverSettings();changed()}catch{status('썸네일 이미지를 읽지 못했습니다.')}};
 const canLeave=()=>!loading&&!saving&&!publishing&&(!dirty||confirm('아직 저장하지 않은 변경 사항이 있습니다. 저장하지 않고 이동할까요?'));
 async function listDrafts(){const records=await draftStore.list(userId);if(!active)return;$('#draft-count').textContent=String(records.length);$('#draft-list').innerHTML=records.length?records.map(r=>`<div class="draft-item"><button type="button" data-load="${esc(r.id)}"><strong>${esc(r.doc.title||'제목 없는 글')}</strong><small>${esc(new Date(r.savedAt).toLocaleString('ko-KR'))}${r.id===draftId?' · 현재 초안':''}</small></button><button type="button" class="outline-btn" data-delete-draft="${esc(r.id)}">삭제</button></div>`).join(''):'<p class="editor-note">저장된 초안이 없습니다.</p>';
  host.querySelectorAll('[data-load]').forEach(b=>b.onclick=async()=>{if(!canLeave())return;const r=await draftStore.get(key(b.dataset.load));if(!r)return;setDocument(r,r.id);$('#draft-current').textContent='불러온 초안: '+(r.doc.title||'제목 없는 글')+' · '+new Date(r.savedAt).toLocaleString('ko-KR');status('초안을 불러왔습니다.');await listDrafts()});
  host.querySelectorAll('[data-delete-draft]').forEach(b=>b.onclick=async()=>{if(saving||publishing||!confirm('이 초안을 삭제할까요? 복구할 수 없습니다.'))return;try{await draftStore.delete(key(b.dataset.deleteDraft));if(draftId===b.dataset.deleteDraft){setDocument({doc:blank()});$('#draft-current').textContent='새 글 · 아직 저장하지 않았습니다.'}await listDrafts();status('초안을 삭제했습니다.')}catch{status('초안을 삭제하지 못했습니다.')}});
 }
 $('#new-post').onclick=()=>{if(canLeave()){setDocument({doc:blank()});$('#draft-current').textContent='새 글 · 아직 저장하지 않았습니다.';history.replaceState(null,'',new URL('write/',document.baseURI));status('새 글을 시작합니다.')}};
 ['title','category','tags'].forEach(name=>$('#edit-'+name).oninput=e=>{doc[name]=e.target.value;changed()});
 const gap=i=>`<div class="insert-gap" data-gap="${i}"><span>여기에 블록 / 이미지 놓기</span><button type="button" data-add-text="${i}">＋ 문단</button><button type="button" data-add-image="${i}">이미지 / GIF</button><button type="button" data-add-video="${i}">링크 삽입</button></div>`;
 function resizeText(){host.querySelectorAll('[data-text]').forEach(t=>{t.style.height='auto';t.style.height=t.scrollHeight+'px'})}
 function renderBlocks(){const node=$('#content-blocks');node.innerHTML=doc.blocks.map((b,i)=>gap(i)+`<section class="content-block ${b.type==='code'?'code-edit-block':''}" data-index="${i}"><button type="button" class="block-drag-handle" data-drag-block="${i}" draggable="true" aria-label="블록 ${i+1} 드래그 이동" title="끌어서 순서 변경 · 방향키로 이동">⠿</button><div class="block-tools">${['paragraph','heading','code','markdown'].includes(b.type)?`<select data-type="${i}" aria-label="블록 유형"><option value="paragraph" ${['paragraph','markdown'].includes(b.type)?'selected':''}>본문</option><option value="heading" ${b.type==='heading'?'selected':''}>소제목</option><option value="code" ${b.type==='code'?'selected':''}>코드</option></select>${b.type==='code'?`<select data-language="${i}" aria-label="코드 언어">${codeLanguages.map(([value,label])=>`<option value="${value}" ${codeLanguage(b.language)===value?'selected':''}>${esc(label)}</option>`).join('')}</select>`:''}`:`<span>${b.type==='image'?'이미지 / GIF':'링크'}</span>`}<button type="button" data-up="${i}" ${i===0?'disabled':''} aria-label="위로 이동">↑</button><button type="button" data-down="${i}" ${i===doc.blocks.length-1?'disabled':''} aria-label="아래로 이동">↓</button><button type="button" data-remove-block="${i}" aria-label="블록 삭제">✕</button></div>${['paragraph','heading','code','markdown'].includes(b.type)?b.type==='code'?`<div class="code-edit-surface"><pre class="code-editor-highlight" aria-hidden="true"><code class="hljs">${highlightCode(b.text,b.language)}</code></pre><textarea data-text="${i}" aria-label="코드 블록 ${i+1}" placeholder="코드를 입력하세요…" rows="6" spellcheck="false" autocapitalize="off" autocomplete="off" wrap="off">${esc(b.text)}</textarea></div>`:`<textarea data-text="${i}" aria-label="본문 블록 ${i+1}" placeholder="내용을 작성하세요…" rows="3">${esc(b.text)}</textarea>`:b.type==='image'?`<div class="media-image-frame"><img class="editor-image" src="${esc(b.src)}" alt="${esc(b.alt)}"></div><input data-alt="${i}" value="${esc(b.alt)}" placeholder="이미지 설명" maxlength="500" aria-label="이미지 설명">`:`<div class="article-body">${renderBlock(b)}</div><button type="button" class="outline-btn" data-video-edit="${i}">표시 방식 변경</button>`}</section>`).join('')+gap(doc.blocks.length);
  node.querySelectorAll('[data-text]').forEach(t=>{const i=Number(t.dataset.text);t.oninput=()=>{doc.blocks[i].text=t.value;if(doc.blocks[i].type==='code')t.closest('.code-edit-surface').querySelector('code').innerHTML=highlightCode(t.value,doc.blocks[i].language);t.style.height='auto';t.style.height=t.scrollHeight+'px';changed()};t.onscroll=()=>{const pre=t.closest('.code-edit-surface')?.querySelector('pre');if(pre){pre.scrollTop=t.scrollTop;pre.scrollLeft=t.scrollLeft}};t.onkeydown=e=>{if(e.key==='Tab'&&!e.shiftKey&&doc.blocks[i].type==='code'){e.preventDefault();const start=t.selectionStart;t.setRangeText('  ',start,t.selectionEnd,'end');t.dispatchEvent(new Event('input',{bubbles:true}));return}if(e.key==='Enter'&&!e.shiftKey&&!['code','markdown'].includes(doc.blocks[i].type)){e.preventDefault();splitText(i,t.selectionStart,t.selectionEnd,[]);focusText(i+1)}};t.onpaste=e=>{const text=e.clipboardData.getData('text/plain').trim();if(safeLink(text)&&!['code','markdown'].includes(doc.blocks[i].type)){e.preventDefault();chooseVideo({index:i,start:t.selectionStart,end:t.selectionEnd},text)}};t.ondragover=e=>e.preventDefault();t.ondrop=e=>{e.preventDefault();e.stopPropagation();const files=[...e.dataTransfer.files];if(files.length)void addImages(files,{index:i,start:t.selectionStart,end:t.selectionEnd})};});
  node.querySelectorAll('[data-type]').forEach(e=>e.onchange=()=>{const i=Number(e.dataset.type);doc.blocks[i].type=e.value;renderBlocks();changed();focusText(i)});
  node.querySelectorAll('[data-language]').forEach(e=>e.onchange=()=>{const i=Number(e.dataset.language);doc.blocks[i].language=e.value;const code=node.querySelector(`[data-index="${i}"] .code-editor-highlight code`);code.innerHTML=highlightCode(doc.blocks[i].text,e.value);changed()});
  node.querySelectorAll('[data-alt]').forEach(e=>e.oninput=()=>{doc.blocks[Number(e.dataset.alt)].alt=e.value;changed()});
  node.querySelectorAll('[data-gap]').forEach(e=>{e.ondragover=x=>{x.preventDefault();e.classList.add('drop-active')};e.ondragleave=()=>e.classList.remove('drop-active');e.ondrop=x=>{x.preventDefault();e.classList.remove('drop-active');if(dragging!==null&&x.dataTransfer.getData('application/x-buiing-block')===dragToken){reorder(dragging,Number(e.dataset.gap));dragging=null}else void addImages([...x.dataTransfer.files],{gap:Number(e.dataset.gap)})}});
  node.querySelectorAll('[data-add-text]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.addText);insert({gap:i},[{type:'paragraph',text:''}]);focusText(i)});
  node.querySelectorAll('[data-add-image]').forEach(b=>b.onclick=()=>{uploadIndex=Number(b.dataset.addImage);$('#body-image-choice').showModal()});
  node.querySelectorAll('[data-add-video]').forEach(b=>b.onclick=()=>chooseVideo({gap:Number(b.dataset.addVideo)}));
  node.querySelectorAll('[data-video-edit]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.videoEdit);chooseVideo({replace:i},doc.blocks[i].url,doc.blocks[i])});
  node.querySelectorAll('[data-remove-block]').forEach(b=>b.onclick=()=>{doc.blocks.splice(Number(b.dataset.removeBlock),1);if(!doc.blocks.length)doc.blocks.push({type:'paragraph',text:''});renderBlocks();changed()});
  node.querySelectorAll('[data-drag-block]').forEach(handle=>{
   handle.ondragstart=e=>{dragging=Number(handle.dataset.dragBlock);e.dataTransfer.setData('application/x-buiing-block',dragToken);e.dataTransfer.effectAllowed='move';handle.closest('.content-block').classList.add('dragging-block')};
   handle.ondragend=()=>{dragging=null;node.querySelectorAll('.drop-active,.dragging-block').forEach(n=>n.classList.remove('drop-active','dragging-block'))};
   handle.onkeydown=e=>{const from=Number(handle.dataset.dragBlock);if(e.key==='ArrowUp'&&from>0){e.preventDefault();reorder(from,from-1);$(`[data-drag-block="${from-1}"]`)?.focus()}if(e.key==='ArrowDown'&&from<doc.blocks.length-1){e.preventDefault();reorder(from,from+2);$(`[data-drag-block="${from+1}"]`)?.focus()}};
   handle.onpointerdown=e=>{if(e.pointerType==='mouse')return;e.preventDefault();dragging=Number(handle.dataset.dragBlock);handle.setPointerCapture(e.pointerId);let target=null;
    handle.onpointermove=x=>{const gaps=[...node.querySelectorAll('[data-gap]')];target=gaps.reduce((best,g)=>Math.abs(g.getBoundingClientRect().top+g.clientHeight/2-x.clientY)<Math.abs(best.getBoundingClientRect().top+best.clientHeight/2-x.clientY)?g:best,gaps[0]);gaps.forEach(g=>g.classList.toggle('drop-active',g===target));if(x.clientY<80)window.scrollBy(0,-16);if(x.clientY>innerHeight-80)window.scrollBy(0,16)};
    const finish=()=>{if(target&&dragging!==null)reorder(dragging,Number(target.dataset.gap));dragging=null;node.querySelectorAll('.drop-active').forEach(g=>g.classList.remove('drop-active'));handle.onpointermove=handle.onpointerup=handle.onpointercancel=null};handle.onpointerup=finish;handle.onpointercancel=()=>{dragging=null;target=null;finish()};
   };
  });
  requestAnimationFrame(resizeText);
  for(const [action,delta] of [['up',-1],['down',1]])node.querySelectorAll('[data-'+action+']').forEach(b=>b.onclick=()=>{const i=Number(b.dataset[action]),j=i+delta;[doc.blocks[i],doc.blocks[j]]=[doc.blocks[j],doc.blocks[i]];renderBlocks();changed()});
 }
 function reorder(from,gap){if(publishing)return;if(moveBlock(doc.blocks,from,gap)){renderBlocks();changed()}}
 function focusText(i){const el=$(`[data-text="${i}"]`);el?.focus();el?.setSelectionRange(0,0)}
 function splitText(index,start,end,items){const b=doc.blocks[index],before={...b,text:b.text.slice(0,start)},after={...b,text:b.text.slice(end)};const parts=items.length?[...(before.text?[before]:[]),...items,...(after.text?[after]:[])]:[before,after];doc.blocks.splice(index,1,...parts);renderBlocks();changed()}
 function insert(where,items){if(where.replace!==undefined){doc.blocks.splice(where.replace,1,...items);renderBlocks();changed()}else if(where.index!==undefined)splitText(where.index,where.start,where.end,items);else{doc.blocks.splice(where.gap,0,...items);renderBlocks();changed()}}
 async function addImages(files,where){const items=[];for(const f of files){if(!['image/png','image/jpeg','image/webp','image/gif'].includes(f.type)||f.size>10485760){status('PNG/JPG/WebP/GIF, 파일당 10MB 이하만 첨부할 수 있습니다.');continue}const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)});items.push({type:'image',src,alt:f.name})}if(items.length)insert(where,items)}
 $('#body-image-cancel').onclick=()=>$('#body-image-choice').close();$('#choose-body-image').onclick=()=>$('#image-upload').click();$('#insert-body-image').onclick=()=>{const src=safeLink($('#body-image-url').value);if(!src||!src.startsWith('https://')){$('#body-image-error').textContent='HTTPS 이미지 주소를 입력해 주세요.';return}insert({gap:uploadIndex},[{type:'image',src,alt:$('#body-image-alt').value}]);$('#body-image-choice').close();$('#body-image-url').value=$('#body-image-alt').value='';$('#body-image-error').textContent=''};
 $('#image-upload').onchange=e=>{void addImages([...e.target.files],{gap:uploadIndex}).catch(()=>status('이미지를 읽지 못했습니다.'));e.target.value='';$('#body-image-choice').close()};
 function chooseVideo(where,url='',block={}){videoInsertion=where;$('#link-description').value=block.description||'';$('#link-thumbnail').value=block.thumbnail||'';$('#youtube-url').value=url;$('#youtube-title').value=block.title||linkDetails(url)?.title||'';$('#youtube-mode').value=block.mode||'embed';$('#video-error').textContent='';$('#youtube-choice').showModal()}
 $('#video-cancel').onclick=()=>$('#youtube-choice').close();$('#confirm-video').onclick=()=>{const info=linkDetails($('#youtube-url').value);if(!info){$('#video-error').textContent='올바른 HTTP / HTTPS 링크 주소를 입력해 주세요.';return}const thumbnail=$('#link-thumbnail').value.trim();if(thumbnail&&(!safeLink(thumbnail)||!thumbnail.startsWith('https://'))){$('#video-error').textContent='썸네일은 HTTPS 이미지 주소를 입력해 주세요.';return}const youtube=youtubeId(info.url);const block={type:youtube&&!$('#link-description').value&&!thumbnail?'youtube':'link',url:info.url,mode:$('#youtube-mode').value,title:$('#youtube-title').value.trim()||info.title};if(block.type==='link'){block.description=$('#link-description').value.trim();block.thumbnail=thumbnail||info.thumbnail}insert(videoInsertion,[block]);$('#youtube-choice').close()};
 $('#youtube-url').oninput=()=>{const info=linkDetails($('#youtube-url').value);if(info&&!$('#youtube-title').value)$('#youtube-title').value=info.title};
 $('#preview-post').onclick=()=>{$('#preview-title').textContent=doc.title;$('#preview-cover').innerHTML=renderCover(doc);$('#preview-body').innerHTML=doc.blocks.map(renderBlock).join('');$('#post-preview').showModal()};$('#close-preview').onclick=()=>$('#post-preview').close();
 async function invoke(body){const {data,error}=await client.functions.invoke('publish-post',{body});if(error){let info;try{info=await error.context?.json()}catch{}throw Error(info?.error||'PUBLISH_SETUP_REQUIRED')}if(data.error)throw Error(data.error);return data}
 const imageCache=new Map();
 async function publishImages(blocks){const result=[];for(const block of blocks){const b={...block};if(b.type==='image'&&b.src.startsWith('data:')){if(imageCache.has(b.src))b.src=imageCache.get(b.src);else{const blob=await(await fetch(b.src)).blob(),ext=blob.type.split('/')[1],path=userId+'/'+crypto.randomUUID()+'.'+ext;const {error}=await client.storage.from('blog-images').upload(path,blob,{contentType:blob.type,cacheControl:'31536000',upsert:false});if(error)throw Error('IMAGE_UPLOAD_FAILED');const {data}=client.storage.from('blog-images').getPublicUrl(path);imageCache.set(b.src,data.publicUrl);b.src=data.publicUrl;}}result.push(b)}return result}
 async function checkDeployment(revision,url,attempt=0){if(!active)return;try{const r=await fetch(new URL('posts.json',document.baseURI),{cache:'no-store'});const posts=await r.json();if(posts.some(p=>p.revision===revision)){$('#publish-result').innerHTML=`<p>게시가 완료됐습니다. <a class="outline-btn" href="${esc(url)}">게시글 보기 ↗</a></p>`;return}}catch{}if(attempt<23)pollTimer=setTimeout(()=>void checkDeployment(revision,url,attempt+1),5000);else $('#publish-result').innerHTML='<p>GitHub 저장은 완료됐습니다. 배포가 아직 확인되지 않았습니다. <a href="https://github.com/rihoyo/buiing_blog/actions" target="_blank" rel="noopener">배포 상태 확인 ↗</a></p>'}
 $('#editor').onsubmit=async e=>{e.preventDefault();const publishStarted=performance.now();if(loadFailed||loading||publishing||!await guard())return;const blocks=doc.blocks.filter(b=>!['paragraph','heading','code','markdown'].includes(b.type)||b.text.trim());if(!doc.title.trim()||!blocks.length){status('제목과 본문을 입력해 주세요.');return}if(dirty)await save();publishing=true;$('#publish-post').disabled=true;updateDirty();status('게시글을 저장하고 있습니다…');let outcome='';try{if(!doc.id)doc.id=crypto.randomUUID();const revision=crypto.randomUUID(),post={...doc,tags:doc.tags.split(',').map(t=>t.trim()).filter(Boolean),blocks:await publishImages(blocks),revision};if(doc.coverImage){const [cover]=await publishImages([{type:'image',src:doc.coverImage,alt:doc.coverAlt||''}]);post.coverImage=cover.src}const result=await invoke({action:'publish',file:file||doc.id+'.json',sha,post});file=file||doc.id+'.json';sha=result.sha;doc.blocks=post.blocks;if(post.coverImage)doc.coverImage=post.coverImage;render();lastSaved='';clearTimeout(pollTimer);if(result.live){outcome=`게시가 완료됐습니다. 저장 소요 ${( (performance.now()-publishStarted)/1000).toFixed(2)}초`;$('#publish-result').innerHTML=`<p>${esc(outcome)} <a class="outline-btn" href="${esc(result.url)}">게시글 보기 ↗</a></p>`}else{outcome='GitHub 저장 완료 · 정적 페이지 배포 중입니다. 즉시 반영 연결을 확인해 주세요.';$('#publish-result').textContent='게시 반영을 확인하고 있습니다…';void checkDeployment(revision,result.url);}status(outcome);}catch(err){outcome=messages[err.message]||(err.message==='IMAGE_UPLOAD_FAILED'?'이미지 업로드에 실패했습니다. blog-images 저장소 설정과 용량을 확인해 주세요.':'게시하지 못했습니다. 초안은 보관돼 있습니다. 연결 설정을 확인해 주세요.');status(outcome)}finally{publishing=false;$('#publish-post').disabled=false;updateDirty();if(dirty)await save();status(outcome)}};
 const beforeUnload=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',beforeUnload);
 const observer=new MutationObserver(()=>{if(!host.isConnected||!host.querySelector('#editor')){active=false;clearTimeout(timer);clearTimeout(pollTimer);window.removeEventListener('beforeunload',beforeUnload);observer.disconnect()}});observer.observe(document.querySelector('#main'),{subtree:true,childList:true});
 try{
  const legacyKey='buiing-admin-draft:'+userId;let legacy=await draftStore.get(legacyKey);if(!legacy){try{legacy=JSON.parse(localStorage.getItem(legacyKey))}catch{}}
  if(legacy){const id='legacy';if(!await draftStore.get(key(id)))await draftStore.put(key(id),{id,owner:userId,savedAt:new Date().toISOString(),doc:{...blank(),title:legacy.title||'',category:legacy.category||'Development',tags:legacy.tags||'',blocks:[...parseText(legacy.text||''),...(legacy.media||[])]},file:null,sha:null});await draftStore.delete(legacyKey);localStorage.removeItem(legacyKey)}
  await listDrafts();
 }catch{status('임시저장 목록을 읽지 못했습니다. 브라우저 저장소 설정을 확인해 주세요.')}
 const edit=new URLSearchParams(location.search).get('edit');
 if(edit){try{const posts=await(await fetch(new URL('posts.json',document.baseURI),{cache:'no-store'})).json();const old=posts.find(p=>p.id===edit);const target=old?.sourceFile||edit+'.json';const result=await invoke({action:'load',file:target});const p=result.post;setDocument({doc:{...p,tags:(p.tags||[]).join(', ')},file:result.file,sha:result.sha});$('#draft-current').textContent='게시글 수정 · 기존 주소를 유지합니다.'}catch(e){status(messages[e.message]||'게시글 원본을 불러오지 못했습니다. 게시 연결 설정을 확인해 주세요.');$('#publish-post').disabled=true;loadFailed=true}}
 else setDocument({doc:blank()});
 loading=false;$('#editor').hidden=false;resizeText();
}
