import {renderCover,defaultTerminalText} from './assets/post-cover.js';
import {escapeHTML as esc,youtubeId,parseText} from './assets/helpers.js';
import {renderBlock} from './assets/post-content.js';
import {draftStore} from './assets/drafts.js';
const blank=()=>({id:'',title:'',category:'Development',tags:'',art:'code',blocks:[{type:'paragraph',text:''}]});
const messages={EDIT_CONFLICT:'다른 곳에서 수정된 글입니다. 초안을 저장한 뒤 최신 게시글을 다시 열어 주세요.',PUBLISH_SETUP_REQUIRED:'게시 연결 설정이 필요합니다. 운영자 설치 안내의 publish-post 설정을 완료해 주세요.',GITHUB_ACCESS_FAILED:'GitHub 연결 권한을 확인해 주세요.',GITHUB_WRITE_FAILED:'GitHub 글 저장에 실패했습니다. 토큰의 Contents 쓰기 권한과 만료일을 확인해 주세요.',FORBIDDEN:'운영자만 게시할 수 있습니다.',LOGIN_REQUIRED:'로그인이 만료됐습니다. 다시 로그인해 주세요.'};
export async function mountBlogEditor({authorize,onDenied,userId,client}){
 const host=document.querySelector('#write-content');
 host.innerHTML=`<section id="editor-dialog" class="write-editor"><div class="dialog-head"><div><span class="eyebrow">WRITE / EDIT</span><h1>기록을 남기세요.</h1></div><a class="outline-btn" href="admin/">관리자 ↗</a></div>
 <details id="draft-panel"><summary>임시저장 목록 <span id="draft-count">0</span></summary><p class="editor-note">이 계정 · 현재 브라우저에 저장됩니다. 브라우저 데이터를 삭제하면 초안도 삭제됩니다.</p><div id="draft-list"></div></details>
 <div class="draft-settings"><label><input id="auto-save" type="checkbox"> 자동 임시저장</label><label>저장 주기 <select id="save-interval"><option value="5">5초</option><option value="15">15초</option><option value="30">30초</option><option value="60">1분</option><option value="300">5분</option></select></label><button id="new-post" class="outline-btn">새 글</button></div>
 <p id="draft-current" class="editor-note">새 글 · 아직 저장하지 않았습니다.</p>
 <form id="editor" hidden><input id="edit-title" placeholder="글 제목" required maxlength="160" aria-label="글 제목"><div class="editor-row"><select id="edit-category" aria-label="카테고리"><option>Development</option><option>Dev Notes</option><option>Tutorial</option></select><input id="edit-tags" placeholder="태그 (쉼표로 구분)" aria-label="태그"></div>
 <fieldset class="cover-settings"><legend>게시글 썸네일</legend><p class="editor-note">메인 추천 글 · 글 목록 · 게시글 상단에 같은 썸네일이 표시됩니다.</p><label>기본 디자인<select id="edit-art"><option value="code">코드 · { ✳ }</option><option value="layers">레이어 · 타일</option><option value="orb">구체</option><option value="terminal">터미널</option></select></label><div class="editor-row"><label>상단 문구<input id="edit-art-label" maxlength="120" placeholder="기본 문구 사용"></label><label>하단 문구<input id="edit-art-caption" maxlength="120" placeholder="기본 문구 사용"></label></div><div id="cover-center-controls"><label><span id="cover-center-label">중앙 내용</span><textarea id="edit-art-center" rows="4" aria-label="サムネイル중앙 내용テキスト"></textarea></label><button type="button" id="reset-cover-text" class="outline-btn">중앙 내용 기본값 복원</button></div><div class="cover-actions"><button type="button" id="choose-cover" class="outline-btn">썸네일 이미지 업로드</button><button type="button" id="remove-cover" class="outline-btn" hidden>이미지 삭제 · 기본 디자인 사용</button></div><input type="file" id="cover-upload" accept="image/png,image/jpeg,image/webp,image/gif" hidden><label id="cover-alt-label" hidden>이미지 설명<input id="edit-cover-alt" maxlength="500"></label><div id="cover-preview"></div></fieldset>
 <p class="editor-note">Enter: 새 문단 · Shift+Enter: 줄바꿈. 이미지/GIF를 문단 사이에 끌어놓거나 YouTube 주소를 붙여넣으세요.</p><div id="content-blocks"></div><input id="image-upload" type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple hidden>
 <div class="editor-bottom"><button class="outline-btn" id="preview-post" type="button">미리보기</button><button class="outline-btn" id="save-draft" type="button" disabled>임시저장</button><button class="black-btn" id="publish-post" type="submit">포스트 게시 ↗</button></div></form><p id="editor-status" role="status"></p><div id="publish-result"></div>
 <dialog id="youtube-choice"><div class="dialog-head"><h2>YouTube 표시 방식</h2><button type="button" id="video-cancel" aria-label="취소">✕</button></div><label>주소<input id="youtube-url" type="url" placeholder="YouTube 주소"></label><label>표시 제목<input id="youtube-title" maxlength="160" placeholder="YouTube 동영상"></label><label>형식<select id="youtube-mode"><option value="embed">임베드 · 여기서 재생</option><option value="url">URL · 주소 그대로</option><option value="mention">멘션 · 짧은 링크</option><option value="bookmark">북마크 · 썸네일 카드</option></select></label><p id="video-error" role="status"></p><button id="confirm-video" class="black-btn">본문에 삽입</button></dialog>
 <dialog id="post-preview"><div class="dialog-head"><h2>게시글 미리보기</h2><button id="close-preview" aria-label="미리보기 닫기">✕</button></div><article class="article"><h1 id="preview-title"></h1><div id="preview-cover"></div><div id="preview-body" class="article-body"></div></article></dialog></section>`;
 const $=s=>host.querySelector(s),prefKey='buiing-draft-options:'+userId;
 let doc=blank(),draftId=crypto.randomUUID(),file=null,sha=null,lastSaved='',timer=null,saving=false,publishing=false,dirty=false,active=true,loading=true,loadFailed=false,uploadIndex=0,videoInsertion=null,pollTimer=null;
 let prefs={auto:true,interval:30};try{prefs={...prefs,...JSON.parse(localStorage.getItem(prefKey)||'{}')}}catch{}
 if(![5,15,30,60,300].includes(Number(prefs.interval)))prefs.interval=30;
 $('#auto-save').checked=!!prefs.auto;$('#save-interval').value=String(prefs.interval);
 const status=text=>{if(active&&$('#editor-status'))$('#editor-status').textContent=text};
 const serialize=()=>JSON.stringify({doc,file,sha});
 const key=id=>userId+'/'+id;
 const guard=async()=>{if(await authorize())return true;active=false;clearTimeout(timer);clearTimeout(pollTimer);await onDenied();return false};
 const persistPrefs=()=>{prefs={auto:$('#auto-save').checked,interval:Number($('#save-interval').value)};try{localStorage.setItem(prefKey,JSON.stringify(prefs))}catch{}clearTimeout(timer);timer=null;updateDirty()};
 $('#auto-save').onchange=$('#save-interval').onchange=persistPrefs;
 function updateDirty(){if(!active)return;dirty=serialize()!==lastSaved;$('#save-draft').disabled=!dirty||saving||publishing;if(!dirty){clearTimeout(timer);timer=null}else if(prefs.auto&&!timer&&!saving&&!publishing)timer=setTimeout(()=>{timer=null;void save()},prefs.interval*1000)}
 async function save(){if(!dirty||saving||publishing||!active)return;clearTimeout(timer);timer=null;saving=true;updateDirty();const snapshot=serialize(),id=draftId;try{const value={owner:userId,id,savedAt:new Date().toISOString(),...JSON.parse(snapshot)};await draftStore.put(key(id),value);if(active&&id===draftId){lastSaved=snapshot;$('#draft-current').textContent='현재 초안: '+(value.doc.title||'제목 없는 글')+' · '+new Date(value.savedAt).toLocaleString('ko-KR');status('임시저장했습니다.');await listDrafts()}}catch{status('임시저장하지 못했습니다. 브라우저 저장 공간과 설정을 확인해 주세요.')}finally{saving=false;updateDirty()}}
 $('#save-draft').onclick=async()=>{if(await guard())await save()};
 const changed=()=>{updateDirty();$('#publish-result').replaceChildren()};
 function render(){ $('#edit-title').value=doc.title;$('#edit-category').value=doc.category;$('#edit-tags').value=doc.tags;$('#publish-post').textContent=file?'수정 사항 게시 ↗':'포스트 게시 ↗';renderCoverSettings();renderBlocks(); }
 function setDocument(value,id=crypto.randomUUID()){loadFailed=false;clearTimeout(pollTimer);$('#publish-result').replaceChildren();clearTimeout(timer);timer=null;doc=structuredClone(value.doc||blank());draftId=id;file=value.file||null;sha=value.sha||null;lastSaved=serialize();render();$('#publish-post').disabled=false;updateDirty()}
 function renderCoverSettings(){
  $('#edit-art').value=doc.art||'code';$('#edit-art-label').value=doc.artLabel??'';$('#edit-art-caption').value=doc.artCaption??'';$('#edit-cover-alt').value=doc.coverAlt||'';updateCenterControls();updateCoverPreview();
 }
 function updateCenterControls(){const terminal=doc.art==='terminal';$('#cover-center-controls').hidden=!!doc.coverImage||!['code','terminal'].includes(doc.art||'code');$('#cover-center-label').textContent=terminal?'터미널 본문 · 줄바꿈 가능':'괄호 안 문자 / 문구';$('#edit-art-center').maxLength=terminal?1000:80;$('#edit-art-center').value=terminal?(doc.artTerminalText??defaultTerminalText):(doc.artCodeText??'✳');$('#edit-art-center').rows=terminal?6:2}
 $('#edit-art-center').oninput=e=>{doc[doc.art==='terminal'?'artTerminalText':'artCodeText']=e.target.value;updateCoverPreview();changed()};
 $('#reset-cover-text').onclick=()=>{delete doc[doc.art==='terminal'?'artTerminalText':'artCodeText'];updateCenterControls();updateCoverPreview();changed()};
 function updateCoverPreview(){const image=!!doc.coverImage;$('#remove-cover').hidden=$('#cover-alt-label').hidden=!image;for(const id of ['#edit-art','#edit-art-label','#edit-art-caption'])$(id).disabled=image;$('#cover-preview').innerHTML=renderCover(doc)}
 for(const [id,field] of [['#edit-art','art'],['#edit-art-label','artLabel'],['#edit-art-caption','artCaption'],['#edit-cover-alt','coverAlt']])$(id).oninput=e=>{if(field==='artLabel'||field==='artCaption'){if(e.target.value)doc[field]=e.target.value;else delete doc[field]}else doc[field]=e.target.value;if(field==='art')updateCenterControls();updateCoverPreview();changed()};
 $('#choose-cover').onclick=()=>$('#cover-upload').click();
 $('#remove-cover').onclick=()=>{delete doc.coverImage;delete doc.coverAlt;renderCoverSettings();changed()};
 $('#cover-upload').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;if(!['image/png','image/jpeg','image/webp','image/gif'].includes(f.type)||f.size>10485760){status('PNG/JPG/WebP/GIF, 10MB 이하의 썸네일만 사용할 수 있습니다.');return}const current=draftId;try{const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)});if(!active||current!==draftId)return;doc.coverImage=src;doc.coverAlt=f.name;renderCoverSettings();changed()}catch{status('썸네일 이미지를 읽지 못했습니다.')}};
 const canLeave=()=>!loading&&!saving&&!publishing&&(!dirty||confirm('아직 저장하지 않은 변경 사항이 있습니다. 저장하지 않고 이동할까요?'));
 async function listDrafts(){const records=await draftStore.list(userId);if(!active)return;$('#draft-count').textContent=String(records.length);$('#draft-list').innerHTML=records.length?records.map(r=>`<div class="draft-item"><button type="button" data-load="${esc(r.id)}"><strong>${esc(r.doc.title||'제목 없는 글')}</strong><small>${esc(new Date(r.savedAt).toLocaleString('ko-KR'))}${r.id===draftId?' · 현재 초안':''}</small></button><button type="button" class="outline-btn" data-delete-draft="${esc(r.id)}">삭제</button></div>`).join(''):'<p class="editor-note">저장된 초안이 없습니다.</p>';
  host.querySelectorAll('[data-load]').forEach(b=>b.onclick=async()=>{if(!canLeave())return;const r=await draftStore.get(key(b.dataset.load));if(!r)return;setDocument(r,r.id);$('#draft-current').textContent='불러온 초안: '+(r.doc.title||'제목 없는 글')+' · '+new Date(r.savedAt).toLocaleString('ko-KR');status('초안을 불러왔습니다.');await listDrafts()});
  host.querySelectorAll('[data-delete-draft]').forEach(b=>b.onclick=async()=>{if(saving||publishing||!confirm('이 초안을 삭제할까요? 복구할 수 없습니다.'))return;try{await draftStore.delete(key(b.dataset.deleteDraft));if(draftId===b.dataset.deleteDraft){setDocument({doc:blank()});$('#draft-current').textContent='새 글 · 아직 저장하지 않았습니다.'}await listDrafts();status('초안을 삭제했습니다.')}catch{status('초안을 삭제하지 못했습니다.')}});
 }
 $('#new-post').onclick=()=>{if(canLeave()){setDocument({doc:blank()});$('#draft-current').textContent='새 글 · 아직 저장하지 않았습니다.';history.replaceState(null,'',new URL('write/',document.baseURI));status('새 글을 시작합니다.')}};
 ['title','category','tags'].forEach(name=>$('#edit-'+name).oninput=e=>{doc[name]=e.target.value;changed()});
 const gap=i=>`<div class="insert-gap" data-gap="${i}"><span>여기에 이미지 놓기</span><button type="button" data-add-text="${i}">＋ 문단</button><button type="button" data-add-image="${i}">이미지 / GIF</button><button type="button" data-add-video="${i}">YouTube</button></div>`;
 function resizeText(){host.querySelectorAll('[data-text]').forEach(t=>{t.style.height='auto';t.style.height=t.scrollHeight+'px'})}
 function renderBlocks(){const node=$('#content-blocks');node.innerHTML=doc.blocks.map((b,i)=>gap(i)+`<section class="content-block" data-index="${i}"><div class="block-tools">${['paragraph','heading','code'].includes(b.type)?`<select data-type="${i}" aria-label="블록 유형"><option value="paragraph" ${b.type==='paragraph'?'selected':''}>본문</option><option value="heading" ${b.type==='heading'?'selected':''}>소제목</option><option value="code" ${b.type==='code'?'selected':''}>코드</option></select>`:`<span>${b.type==='image'?'이미지 / GIF':'YouTube'}</span>`}<button type="button" data-up="${i}" ${i===0?'disabled':''} aria-label="위로 이동">↑</button><button type="button" data-down="${i}" ${i===doc.blocks.length-1?'disabled':''} aria-label="아래로 이동">↓</button><button type="button" data-remove-block="${i}" aria-label="블록 삭제">✕</button></div>${['paragraph','heading','code'].includes(b.type)?`<textarea data-text="${i}" aria-label="본문 블록 ${i+1}" placeholder="내용을 작성하세요…" rows="${b.type==='code'?6:3}">${esc(b.text)}</textarea>`:b.type==='image'?`<img class="editor-image" src="${esc(b.src)}" alt="${esc(b.alt)}"><input data-alt="${i}" value="${esc(b.alt)}" placeholder="이미지 설명" maxlength="500" aria-label="이미지 설명">`:`<div class="article-body">${renderBlock(b)}</div><button type="button" class="outline-btn" data-video-edit="${i}">표시 방식 변경</button>`}</section>`).join('')+gap(doc.blocks.length);
  node.querySelectorAll('[data-text]').forEach(t=>{const i=Number(t.dataset.text);t.oninput=()=>{doc.blocks[i].text=t.value;t.style.height='auto';t.style.height=t.scrollHeight+'px';changed()};t.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&doc.blocks[i].type!=='code'){e.preventDefault();splitText(i,t.selectionStart,t.selectionEnd,[]);focusText(i+1)}};t.onpaste=e=>{const text=e.clipboardData.getData('text/plain').trim();if(youtubeId(text)){e.preventDefault();chooseVideo({index:i,start:t.selectionStart,end:t.selectionEnd},text)}};t.ondragover=e=>e.preventDefault();t.ondrop=e=>{e.preventDefault();e.stopPropagation();const files=[...e.dataTransfer.files];if(files.length)void addImages(files,{index:i,start:t.selectionStart,end:t.selectionEnd})};});
  node.querySelectorAll('[data-type]').forEach(e=>e.onchange=()=>{doc.blocks[Number(e.dataset.type)].type=e.value;changed()});
  node.querySelectorAll('[data-alt]').forEach(e=>e.oninput=()=>{doc.blocks[Number(e.dataset.alt)].alt=e.value;changed()});
  node.querySelectorAll('[data-gap]').forEach(e=>{e.ondragover=x=>{x.preventDefault();e.classList.add('drop-active')};e.ondragleave=()=>e.classList.remove('drop-active');e.ondrop=x=>{x.preventDefault();e.classList.remove('drop-active');void addImages([...x.dataTransfer.files],{gap:Number(e.dataset.gap)})}});
  node.querySelectorAll('[data-add-text]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.addText);insert({gap:i},[{type:'paragraph',text:''}]);focusText(i)});
  node.querySelectorAll('[data-add-image]').forEach(b=>b.onclick=()=>{uploadIndex=Number(b.dataset.addImage);$('#image-upload').click()});
  node.querySelectorAll('[data-add-video]').forEach(b=>b.onclick=()=>chooseVideo({gap:Number(b.dataset.addVideo)}));
  node.querySelectorAll('[data-video-edit]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.videoEdit);chooseVideo({replace:i},doc.blocks[i].url,doc.blocks[i])});
  node.querySelectorAll('[data-remove-block]').forEach(b=>b.onclick=()=>{doc.blocks.splice(Number(b.dataset.removeBlock),1);if(!doc.blocks.length)doc.blocks.push({type:'paragraph',text:''});renderBlocks();changed()});
  requestAnimationFrame(resizeText);
  for(const [action,delta] of [['up',-1],['down',1]])node.querySelectorAll('[data-'+action+']').forEach(b=>b.onclick=()=>{const i=Number(b.dataset[action]),j=i+delta;[doc.blocks[i],doc.blocks[j]]=[doc.blocks[j],doc.blocks[i]];renderBlocks();changed()});
 }
 function focusText(i){const el=$(`[data-text="${i}"]`);el?.focus();el?.setSelectionRange(0,0)}
 function splitText(index,start,end,items){const b=doc.blocks[index],before={...b,text:b.text.slice(0,start)},after={...b,text:b.text.slice(end)};const parts=items.length?[...(before.text?[before]:[]),...items,...(after.text?[after]:[])]:[before,after];doc.blocks.splice(index,1,...parts);renderBlocks();changed()}
 function insert(where,items){if(where.replace!==undefined){doc.blocks.splice(where.replace,1,...items);renderBlocks();changed()}else if(where.index!==undefined)splitText(where.index,where.start,where.end,items);else{doc.blocks.splice(where.gap,0,...items);renderBlocks();changed()}}
 async function addImages(files,where){const items=[];for(const f of files){if(!['image/png','image/jpeg','image/webp','image/gif'].includes(f.type)||f.size>10485760){status('PNG/JPG/WebP/GIF, 파일당 10MB 이하만 첨부할 수 있습니다.');continue}const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)});items.push({type:'image',src,alt:f.name})}if(items.length)insert(where,items)}
 $('#image-upload').onchange=e=>{void addImages([...e.target.files],{gap:uploadIndex}).catch(()=>status('이미지를 읽지 못했습니다.'));e.target.value=''};
 function chooseVideo(where,url='',block={}){videoInsertion=where;$('#youtube-url').value=url;$('#youtube-title').value=block.title||'';$('#youtube-mode').value=block.mode||'embed';$('#video-error').textContent='';$('#youtube-choice').showModal()}
 $('#video-cancel').onclick=()=>$('#youtube-choice').close();$('#confirm-video').onclick=()=>{const id=youtubeId($('#youtube-url').value.trim());if(!id){$('#video-error').textContent='올바른 YouTube 주소를 입력해 주세요.';return}insert(videoInsertion,[{type:'youtube',url:'https://www.youtube.com/watch?v='+id,mode:$('#youtube-mode').value,title:$('#youtube-title').value.trim()}]);$('#youtube-choice').close()};
 $('#preview-post').onclick=()=>{$('#preview-title').textContent=doc.title;$('#preview-cover').innerHTML=renderCover(doc);$('#preview-body').innerHTML=doc.blocks.map(renderBlock).join('');$('#post-preview').showModal()};$('#close-preview').onclick=()=>$('#post-preview').close();
 async function invoke(body){const {data,error}=await client.functions.invoke('publish-post',{body});if(error){let info;try{info=await error.context?.json()}catch{}throw Error(info?.error||'PUBLISH_SETUP_REQUIRED')}if(data.error)throw Error(data.error);return data}
 const imageCache=new Map();
 async function publishImages(blocks){const result=[];for(const block of blocks){const b={...block};if(b.type==='image'&&b.src.startsWith('data:')){if(imageCache.has(b.src))b.src=imageCache.get(b.src);else{const blob=await(await fetch(b.src)).blob(),ext=blob.type.split('/')[1],path=userId+'/'+crypto.randomUUID()+'.'+ext;const {error}=await client.storage.from('blog-images').upload(path,blob,{contentType:blob.type,cacheControl:'31536000',upsert:false});if(error)throw Error('IMAGE_UPLOAD_FAILED');const {data}=client.storage.from('blog-images').getPublicUrl(path);imageCache.set(b.src,data.publicUrl);b.src=data.publicUrl;}}result.push(b)}return result}
 async function checkDeployment(revision,url,attempt=0){if(!active)return;try{const r=await fetch(new URL('posts.json',document.baseURI),{cache:'no-store'});const posts=await r.json();if(posts.some(p=>p.revision===revision)){$('#publish-result').innerHTML=`<p>게시가 완료됐습니다. <a class="outline-btn" href="${esc(url)}">게시글 보기 ↗</a></p>`;return}}catch{}if(attempt<23)pollTimer=setTimeout(()=>void checkDeployment(revision,url,attempt+1),5000);else $('#publish-result').innerHTML='<p>GitHub 저장은 완료됐습니다. 배포가 아직 확인되지 않았습니다. <a href="https://github.com/rihoyo/buiing_blog/actions" target="_blank" rel="noopener">배포 상태 확인 ↗</a></p>'}
 $('#editor').onsubmit=async e=>{e.preventDefault();const publishStarted=performance.now();if(loadFailed||loading||publishing||!await guard())return;const blocks=doc.blocks.filter(b=>!['paragraph','heading','code'].includes(b.type)||b.text.trim());if(!doc.title.trim()||!blocks.length){status('제목과 본문을 입력해 주세요.');return}if(dirty)await save();publishing=true;$('#publish-post').disabled=true;updateDirty();status('게시글을 저장하고 있습니다…');let outcome='';try{if(!doc.id)doc.id=crypto.randomUUID();const revision=crypto.randomUUID(),post={...doc,tags:doc.tags.split(',').map(t=>t.trim()).filter(Boolean),blocks:await publishImages(blocks),revision};if(doc.coverImage){const [cover]=await publishImages([{type:'image',src:doc.coverImage,alt:doc.coverAlt||''}]);post.coverImage=cover.src}const result=await invoke({action:'publish',file:file||doc.id+'.json',sha,post});file=file||doc.id+'.json';sha=result.sha;doc.blocks=post.blocks;if(post.coverImage)doc.coverImage=post.coverImage;render();lastSaved='';clearTimeout(pollTimer);if(result.live){outcome=`게시가 완료됐습니다. 저장 소요 ${( (performance.now()-publishStarted)/1000).toFixed(2)}초`;$('#publish-result').innerHTML=`<p>${esc(outcome)} <a class="outline-btn" href="${esc(result.url)}">게시글 보기 ↗</a></p>`}else{outcome='GitHub 저장 완료 · 정적 페이지 배포 중입니다. 즉시 반영 연결을 확인해 주세요.';$('#publish-result').textContent='게시 반영을 확인하고 있습니다…';void checkDeployment(revision,result.url);}status(outcome);}catch(err){outcome=messages[err.message]||(err.message==='IMAGE_UPLOAD_FAILED'?'이미지 업로드에 실패했습니다. blog-images 저장소 설정과 용량을 확인해 주세요.':'게시하지 못했습니다. 초안은 보관돼 있습니다. 연결 설정을 확인해 주세요.');status(outcome)}finally{publishing=false;$('#publish-post').disabled=false;updateDirty();if(dirty)await save();status(outcome)}};
 const beforeUnload=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',beforeUnload);
 const observer=new MutationObserver(()=>{if(!host.isConnected||!host.querySelector('#editor')){active=false;clearTimeout(timer);clearTimeout(pollTimer);window.removeEventListener('beforeunload',beforeUnload);observer.disconnect()}});observer.observe(document.querySelector('#main'),{subtree:true,childList:true});
 try{
  const legacyKey='buiing-admin-draft:'+userId;let legacy=await draftStore.get(legacyKey);if(!legacy){try{legacy=JSON.parse(localStorage.getItem(legacyKey))}catch{}}
  if(legacy){const id='legacy';if(!await draftStore.get(key(id)))await draftStore.put(key(id),{id,owner:userId,savedAt:new Date().toISOString(),doc:{...blank(),title:legacy.title||'',category:legacy.category||'Development',tags:legacy.tags||'',blocks:[...parseText(legacy.text||''),...(legacy.media||[])]},file:null,sha:null});await draftStore.delete(legacyKey);localStorage.removeItem(legacyKey)}
  await listDrafts();
 }catch{status('임시저장 목록을 읽지 못했습니다. 브라우저 저장소 설정을 확인해 주세요.')}
 const edit=new URLSearchParams(location.search).get('edit');
 if(edit){try{const posts=await(await fetch(new URL('posts.json',document.baseURI),{cache:'no-store'})).json();const old=posts.find(p=>p.id===edit);const target=old?.sourceFile||edit+'.json';const result=await invoke({action:'load',file:target});const p=result.post;setDocument({doc:{...p,tags:(p.tags||[]).join(', ')},file:result.file,sha:result.sha});$('#draft-current').textContent='게시글 수정 · 기존 주소를 유지합니다.'}catch(e){status(messages[e.message]||'게시글 원본을 불러오지 못했습니다. 게시 연결 설정을 확인해 주세요.');$('#publish-post').disabled=true;loadFailed=true}}
 else setDocument({doc:blank()});
 loading=false;$('#editor').hidden=false;resizeText();
}
