import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const base=process.env.BLOG_TEST_URL||'http://localhost:3000/buiing_blog/';
const page=await browser.newPage({viewport:{width:1440,height:1080}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const posts=await(await page.request.get(new URL('posts.json',base).href)).json();
await page.route('**/rest/v1/published_posts**',r=>r.fulfill({status:404,json:{}}));
await page.goto(base);await page.locator('.card').first().waitFor();await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'/tmp/buiing-desktop.png',fullPage:true});
assert.equal(await page.locator('.card').count(),posts.length);
await page.getByRole('button',{name:'Tutorial'}).click();assert.equal(await page.locator('.card').count(),posts.filter(p=>p.category==='Tutorial').length);
await page.locator('#list-search').fill('not found');assert.equal(await page.locator('.card').count(),0);
await page.locator('#list-search').fill('');await page.locator('.card').filter({hasText:'Grid'}).first().click();await page.locator('.article h1').waitFor();assert.match(await page.locator('.article h1').textContent(),/Grid/);
await page.getByRole('button',{name:'글 검색',exact:true}).click();await page.locator('#global-search').fill('Git');assert.ok(await page.locator('.search-result').count()>=1);await page.locator('.search-result').filter({hasText:'Git'}).first().click();await page.waitForFunction(()=>document.querySelector('.article h1')?.textContent.includes('Git'));assert.match(await page.locator('.article h1').textContent(),/Git/);
await page.locator('#theme-toggle').click();assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('dark')),true);await page.locator('#theme-toggle').click();
assert.equal(await page.locator('#write-button').isVisible(),false);assert.equal(await page.locator('#editor-dialog').count(),0);
await page.goto(base+'about/');await page.locator('.about').waitFor();
await page.setViewportSize({width:390,height:844});await page.goto(base);await page.locator('.card').first().waitFor();await page.screenshot({path:'/tmp/buiing-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('#write-button').isVisible(),false);assert.equal(await page.locator('#editor-dialog').count(),0);
assert.deepEqual(errors,[]);console.log('Desktop/mobile, filters, search, article, theme, and anonymous editor exclusion: passed');await browser.close();
