import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const context=await browser.newContext();const page=await context.newPage({viewport:{width:1200,height:900}});
const base=process.env.BLOG_TEST_URL||'http://localhost:3000/buiing_blog/';const id='00000000-0000-4000-8000-000000000001';const errors=[];page.on('pageerror',e=>errors.push(e.message));
const jwt=['eyJhbGciOiJIUzI1NiJ9',Buffer.from(JSON.stringify({sub:id,role:'authenticated',exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'test'].join('.');
let entries=[],settings={blocked_words:[],filter_mode:'reject'},loggedIn=false,isOwner=true,adminReads=0;let methods=['email'],authorizeUrl=null;
await context.route('**/config.json',r=>r.fulfill({json:{supabaseUrl:'https://test.supabase.co',supabasePublishableKey:'test-public-key',loginMethods:methods}}));
let guestEntries=[];
await context.route('https://test.supabase.co/**',async r=>{const path=new URL(r.request().url()).pathname;let body;try{body=r.request().postDataJSON()}catch{};const send=json=>r.fulfill({json});
 if(path.endsWith('/authorize')){authorizeUrl=new URL(r.request().url());return r.fulfill({contentType:'text/html',body:'OAuth provider test page'})}
 if(path.endsWith('/otp'))return send({});
 if(path.endsWith('/verify')){loggedIn=true;return send({access_token:jwt,refresh_token:'test-refresh',token_type:'bearer',expires_in:3600,user:{id,email:'admin@example.com',aud:'authenticated',role:'authenticated',user_metadata:{display_name:'관리자'},app_metadata:{provider:'email'}}})}
 if(path.endsWith('/logout')){loggedIn=false;return send({})}
 if(path.endsWith('/rpc/is_admin'))return send(loggedIn&&isOwner);
 if(path.endsWith('/rpc/create_entry')){const e={id:crypto.randomUUID(),author_id:id,author_name:'관리자',kind:body.p_kind,title:body.p_title,body:body.p_body,blog_slug:body.p_blog_slug,thread_id:body.p_thread_id,created_at:new Date().toISOString(),deleted_at:null};entries.unshift(e);return send(e.id)}
 if(path.endsWith('/rpc/delete_entry')){entries=entries.filter(e=>e.id!==body.p_id);return send(null)}
 if(path.endsWith('/rpc/admin_state')){adminReads++;return loggedIn&&isOwner?send({settings,bans:[],audit:[]}):r.fulfill({status:403,json:{message:'FORBIDDEN'}})}
 if(path.endsWith('/rpc/admin_settings')){settings={blocked_words:body.p_words,filter_mode:body.p_mode};return send(null)}
 if(path.includes('/functions/v1/guest-interactions')){if(body.action==='create'){const id=crypto.randomUUID();guestEntries.unshift({id,scope:body.scope,blog_slug:body.slug,thread_id:body.thread,root_id:id,parent_id:null,author_name:body.name,body:body.body,likes:0,created_at:new Date().toISOString()});return send({id})}return send({deleted:true,likes:1})}
 if(path.endsWith('/guest_entries')){const u=new URL(r.request().url());let rows=guestEntries;for(const key of ['scope','blog_slug','thread_id']){const q=u.searchParams.get(key);if(q?.startsWith('eq.'))rows=rows.filter(e=>e[key]===q.slice(3))}if(u.searchParams.get('parent_id')==='not.is.null')rows=[];return send(rows)}
 if(path.endsWith('/entries')){const u=new URL(r.request().url());let rows=entries;for(const key of ['id','kind','thread_id','blog_slug']){const q=u.searchParams.get(key);if(q?.startsWith('eq.'))rows=rows.filter(e=>e[key]===q.slice(3))}return send(r.request().headers().accept?.includes('object')?(rows[0]||null):rows)}
 return r.fulfill({status:400,json:{message:'Unexpected request '+path}});
});
try{
 await page.goto(base+'community/?board=members');await page.locator('#auth-button').click();await page.locator('#login-form input[name=name]').fill('관리자');await page.locator('#login-form input[name=email]').fill('admin@example.com');await page.locator('#login-form button').click();await page.locator('#verify-form input').fill('123456');await page.locator('#verify-form button').click();await expect(page.locator('#compose-form')).toBeVisible();
 await page.locator('#compose-form input').fill('커뮤니티 테스트');await page.locator('#compose-form textarea').fill('<script>alert("unsafe")</script>');await page.locator('#compose-form button').click();await expect(page.locator('.visitor-entry h3')).toHaveText('커뮤니티 테스트');await expect(page.locator('.visitor-body')).toHaveText('<script>alert("unsafe")</script>');
 await page.locator('.visitor-entry h3 a').click();await expect(page.locator('#compose-form')).toBeVisible();await page.locator('#compose-form textarea').fill('방문자 댓글');await page.locator('#compose-form button').click();await expect(page.locator('#thread-comments')).toContainText('방문자 댓글');
 await page.goto(base+'admin/');await expect(page.locator('#filter-form')).toBeVisible();await page.locator('#filter-form .token-draft').fill('금칙어,광고문자,');await page.locator('#filter-form select').selectOption('mask');await page.locator('#filter-form button.black-btn').click();await expect(page.locator('#filter-status')).toHaveText('설정을 저장했습니다.');assert.deepEqual(settings.blocked_words,['금칙어','광고문자']);
 await expect(page.locator('#admin-write-button')).toHaveAttribute('href','write/');
 page.on('dialog',d=>d.accept());await page.locator('[data-delete]').first().click();await expect(page.locator('#admin-entries .visitor-entry')).toHaveCount(1);
 await page.goto(base+'posts/react-thinking/');await expect(page.locator('#comments .guest-compose')).toBeVisible();await page.locator('#comments .guest-compose textarea').fill('블로그 댓글');await page.locator('#comments input[name=nickname]').fill('비회원');await page.locator('#comments .guest-compose input[name=password]').fill('password123');await page.locator('#comments .guest-compose button.black-btn').click();await expect(page.locator('#comments .guest-list')).toContainText('블로그 댓글');
 await page.setViewportSize({width:390,height:844});await page.goto(base+'community/?board=members');await expect(page.locator('#compose-form')).toBeVisible();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/community-mobile.png',fullPage:true});
 await page.locator('#auth-button').click();await page.goto(base+'admin/');await expect(page.locator('#admin-content')).toContainText('관리자 계정으로 로그인');assert.equal(await page.locator('#filter-form').count(),0);

 // A logged-in ordinary member may write community posts, but never gets the editor.
 isOwner=false;await page.locator('#auth-button').click();await page.locator('#login-form input[name=name]').fill('회원');await page.locator('#login-form input[name=email]').fill('member@example.com');await page.locator('#login-form button').click();await page.locator('#verify-form input').fill('123456');await page.locator('#verify-form button').click();await expect(page.locator('#admin-content')).toContainText('접근 권한이 없습니다');
 const memberReads=adminReads;await page.evaluate(()=>{localStorage.setItem('is_admin','true');localStorage.setItem('role','admin')});
 await page.goto(base+'write/');await expect(page.locator('#write-content')).toContainText('운영자 전용 글쓰기');await page.goto(base+'admin/');await expect(page.locator('#admin-content')).toContainText('접근 권한이 없습니다');assert.equal(adminReads,memberReads);assert.equal(await page.locator('#editor-dialog').count(),0);await expect(page.locator('#write-button')).toBeHidden();await expect(page.locator('.admin-link')).toBeHidden();
 await page.goto(base+'community/?board=members');await expect(page.locator('#compose-form')).toBeVisible();await page.locator('#compose-form input').fill('회원 커뮤니티 글');await page.locator('#compose-form textarea').fill('회원은 이곳에서 작성할 수 있습니다.');await page.locator('#compose-form button').click();await expect(page.locator('#thread-list')).toContainText('회원 커뮤니티 글');
 // A formerly authorized editor cannot publish after its server role is revoked.
 isOwner=true;await page.goto(base+'write/');await expect(page.locator('.write-editor')).toBeVisible();await page.locator('#edit-title').fill('권한 회수 테스트');await page.locator('[data-text="0"]').fill('회수 후 발행 불가');isOwner=false;
 let unauthorizedDownloads=0;page.on('download',()=>unauthorizedDownloads++);await page.locator('#editor button[type=submit]').click();await expect(page.locator('#write-content')).toContainText('운영자 전용 글쓰기');assert.equal(unauthorizedDownloads,0);assert.equal(await page.locator('#editor-dialog').count(),0);

 // Default free Google OAuth uses PKCE and redirects only to this site's page.
 await page.goto(base+'admin/');await page.locator('#auth-button').click();await expect(page.locator('#auth-button')).toHaveText('관리자 로그인');methods=['google'];await page.goto(base);await page.locator('#account-button').click();await expect(page.locator('#google-login')).toBeVisible();assert.equal(await page.locator('#login-form').count(),0);
 await page.locator('#google-login').click();await page.waitForURL('https://test.supabase.co/auth/v1/authorize**');assert.equal(authorizeUrl.searchParams.get('provider'),'google');assert.equal(authorizeUrl.searchParams.get('redirect_to'),base);assert.ok(authorizeUrl.searchParams.get('code_challenge'));assert.equal(authorizeUrl.searchParams.get('code_challenge_method').toLowerCase(),'s256');assert.ok(!authorizeUrl.searchParams.get('scopes')?.includes('repo'));
 const nojs=await browser.newContext({javaScriptEnabled:false});const crawler=await nojs.newPage();await crawler.goto(base+'posts/react-thinking/');await expect(crawler.locator('h1')).toContainText('컴포넌트');await expect(crawler.locator('.article-body')).toContainText('함께 바뀌는');assert.equal(await crawler.locator('link[rel=canonical]').getAttribute('href'),'https://rihoyo.github.io/buiing_blog/posts/react-thinking/');await nojs.close();assert.deepEqual(errors,[]);console.log('Mocked auth UI passed: anonymous/member/admin separation, admin-only publishing access, revocation, spoofed role rejection, community/comment permissions, moderation, mobile and no-JS SEO.');
}finally{await browser.close()}
