import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
test('Approval, empty-password credential edits, strict nickname/blog filters and admin-only activity are enforced',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email_confirmed_at timestamptz,raw_user_meta_data jsonb);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated;`);
 for(const p of ['schema.sql','guest-community.sql','community-upgrade.sql','community-upgrade.sql','community-editing.sql','community-editing.sql'])await db.exec(await readFile('supabase/'+p,'utf8'));
 const member='00000000-0000-4000-8000-000000000001',owner='00000000-0000-4000-8000-000000000002';await db.query("insert into auth.users values($1,now(),'{\"display_name\":\"member\"}'),($2,now(),'{\"display_name\":\"owner\"}')",[member,owner]);await db.query('insert into private.admins values($1)',[owner]);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[member]);await db.exec('set role authenticated');
 const thread=(await db.query("select create_entry('thread','hello','body') as id")).rows[0].id;assert.equal((await db.query('select moderation_status from entries where id=$1',[thread])).rows[0].moderation_status,'pending');await assert.rejects(()=>db.query('select admin_moderate_thread($1,true)',[thread]),/FORBIDDEN/);await assert.rejects(()=>db.query('select admin_community_dashboard()'),/FORBIDDEN/);await assert.rejects(()=>db.exec('select * from private.community_activity'),/permission denied/);
 await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub','',false)");await db.exec('set role anon');assert.equal((await db.query('select * from entries')).rows.length,0);
 await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);await db.exec('set role authenticated');await db.query('select admin_moderate_thread($1,true)',[thread]);await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub','',false)");await db.exec('set role anon');assert.equal((await db.query('select * from entries')).rows.length,1);
 await db.exec('reset role;set role service_role');const actor='a'.repeat(64),hash='b'.repeat(64);const guest=(await db.query("select secure_guest_create('guestbook',null,null,null,'guest','**hello**',$1,$2,$3) as id",['c'.repeat(32),hash,actor])).rows[0].id;assert.equal((await db.query('select secure_guest_edit($1,$2,$3,$4) as edited',[guest,'wrong','changed',actor])).rows[0].edited,false);assert.equal((await db.query('select secure_guest_edit($1,$2,$3,$4) as edited',[guest,hash,'**changed**',actor])).rows[0].edited,true);
 await db.exec('reset role');assert.ok((await db.query('select edited_at from guest_entries where id=$1',[guest])).rows[0].edited_at);await db.exec("update private.settings set blocked_words=array['bad']");await db.exec('set role service_role');await assert.rejects(()=>db.query("select secure_guest_create('guestbook',null,null,null,'bad nickname','okay',$1,$2,$3)",['c'.repeat(32),hash,actor]),/BLOCKED_WORD/);await assert.rejects(()=>db.query('select secure_guest_edit($1,$2,$3,$4)',[guest,hash,'bad content',actor]),/BLOCKED_WORD/);
 await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);await db.exec('set role authenticated');await assert.rejects(()=>db.query("select validate_blog_words('{\"blocks\":[{\"text\":\"bad\"}]}')"),/BLOCKED_WORD/);const dashboard=(await db.query('select admin_community_dashboard() as data')).rows[0].data;assert.equal(dashboard.stats.threads,1);assert.ok(dashboard.activity.some(a=>a.action==='edit'));assert.ok(dashboard.activity.some(a=>a.action==='thread_approved'));assert.ok(!JSON.stringify(dashboard).includes(hash));await db.query("select set_config('request.jwt.claim.sub',$1,false)",[member]);const edited=(await db.query('select edit_entry($1,$2,$3) as result',[thread,'Changed title','Changed body'])).rows[0].result;assert.equal(edited.changed,true);assert.equal(edited.pending,true);assert.ok(edited.edited_at);const unchanged=(await db.query('select edit_entry($1,$2,$3) as result',[thread,'Changed title','Changed body'])).rows[0].result;assert.equal(unchanged.changed,false);assert.equal(unchanged.edited_at,edited.edited_at);await assert.rejects(()=>db.query('select edit_entry($1,$2,$3)',[thread,'bad title','body']),/BLOCKED_WORD/);await db.query("select set_config('request.jwt.claim.sub',$1,false)",['00000000-0000-4000-8000-000000000003']);await assert.rejects(()=>db.query('select edit_entry($1,$2,$3)',[thread,'hijack','body']),/FORBIDDEN/);await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub','',false)");await db.exec('set role anon');assert.equal((await db.query('select * from entries where id=$1',[thread])).rows.length,0);await assert.rejects(()=>db.query('select edit_entry($1,$2,$3)',[thread,'hijack','body']),/permission denied/);
 }finally{await db.close()}
});
