import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1200,height:950}}),page=await context.newPage();
const base=process.env.BLOG_TEST_URL||'http://localhost:3100/buiing_blog/',id='00000000-0000-4000-8000-000000000001';
const jwt=['eyJhbGciOiJIUzI1NiJ9',Buffer.from(JSON.stringify({sub:id,role:'authenticated',exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'test'].join('.');
let admin=true,published=[],fail=false,uploads=0;const errors=[];page.on('pageerror',e=>errors.push(e.message));
const sample={id:'react-thinking',title:'원래 글',category:'Development',tags:['React'],date:'2026-01-01',sourceFile:'react-thinking.json',blocks:[{type:'paragraph',text:'기존 본문'}]};
await context.addInitScript(({jwt,id,origin})=>{if(location.origin!==origin)return;localStorage.setItem('sb-test-auth-token',JSON.stringify({access_token:jwt,refresh_token:'refresh',expires_at:Math.floor(Date.now()/1000)+3600,token_type:'bearer',user:{id,email:'owner@example.com',aud:'authenticated',role:'authenticated'}}))},{jwt,id,origin:new URL(base).origin});
await context.route('**/config.json',r=>r.fulfill({json:{supabaseUrl:'https://test.supabase.co',supabasePublishableKey:'public',loginMethods:['google']}}));
await context.route('**/posts.json',r=>r.fulfill({json:[sample,...published.map(p=>({...p.post,date:'2026-10-04'}))]}));
await context.route('https://test.supabase.co/**',r=>{const path=new URL(r.request().url()).pathname;if(path.endsWith('/rpc/is_admin'))return r.fulfill({json:admin});if(path.includes('/functions/v1/publish-post')){const body=r.request().postDataJSON();if(!admin)return r.fulfill({status:403,json:{error:'FORBIDDEN'}});if(fail)return r.fulfill({status:503,json:{error:'PUBLISH_SETUP_REQUIRED'}});if(body.action==='load')return r.fulfill({json:{post:sample,sha:'old-sha',file:sample.sourceFile}});published.push(body);return r.fulfill({json:{sha:'new-sha',revision:body.post.revision,url:base+'posts/'+body.post.id+'/'}})}if(path.includes('/storage/v1/object/')){if(r.request().method()==='POST')uploads++;return r.fulfill({json:{Key:'image.gif'}})}return r.fulfill({json:[]})});
try{
 await page.goto(base+'write/');await expect(page.locator('#save-draft')).toBeDisabled();await page.locator('#auto-save').uncheck();await page.locator('#edit-title').fill('첫 초안');await page.locator('[data-text="0"]').fill('첫 문단');await expect(page.locator('#save-draft')).toBeEnabled();await page.locator('#save-draft').click();await expect(page.locator('#save-draft')).toBeDisabled();await expect(page.locator('#draft-count')).toHaveText('1');
 await page.locator('#edit-title').fill('수정');await expect(page.locator('#save-draft')).toBeEnabled();await page.locator('#edit-title').fill('첫 초안');await expect(page.locator('#save-draft')).toBeDisabled();
 await page.locator('#new-post').click();await page.locator('#edit-title').fill('두 번째 초안');await page.locator('[data-text="0"]').fill('다른 내용');await page.locator('#save-draft').click();await expect(page.locator('#draft-count')).toHaveText('2');
 await page.reload();await expect(page.locator('#edit-title')).toHaveValue('');await expect(page.locator('#auto-save')).not.toBeChecked();await page.locator('#draft-panel summary').click();await page.locator('[data-load]').filter({hasText:'첫 초안'}).click();await expect(page.locator('[data-text="0"]')).toHaveValue('첫 문단');
 await page.locator('#auto-save').check();await page.locator('#save-interval').selectOption('5');await page.locator('#edit-title').fill('자동으로 저장된 제목');await expect(page.locator('#save-draft')).toBeDisabled({timeout:8000});await expect(page.locator('[data-load]').filter({hasText:'자동으로 저장된 제목'})).toBeVisible();await page.locator('#auto-save').uncheck();
 await page.locator('[data-text="0"]').fill('앞 문단뒤 문단');await page.locator('[data-text="0"]').evaluate(e=>e.setSelectionRange(4,4));await page.locator('[data-text="0"]').press('Enter');await expect(page.locator('[data-text]')).toHaveCount(2);
 await page.locator('[data-gap="1"]').evaluate(el=>{const data=new DataTransfer();data.items.add(new File([Uint8Array.from(atob('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'),c=>c.charCodeAt(0))],'pixel.gif',{type:'image/gif'}));el.dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:data}))});await expect(page.locator('.editor-image')).toBeVisible();
 // Paste a common YouTube URL into the second text block.
 await page.locator('[data-text="2"]').evaluate(el=>{el.setSelectionRange(0,0);const data=new DataTransfer();data.setData('text/plain','https://youtu.be/dQw4w9WgXcQ');el.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,clipboardData:data}))});await expect(page.locator('#youtube-choice')).toBeVisible();await page.locator('#youtube-mode').selectOption('bookmark');await page.locator('#youtube-title').fill('영상 제목');await page.locator('#confirm-video').click();await expect(page.locator('.video-bookmark')).toBeVisible();
 for(const mode of ['url','mention','embed','bookmark']){await page.locator('[data-video-edit]').click();await page.locator('#youtube-mode').selectOption(mode);await page.locator('#confirm-video').click();const selector={url:'.video-url',mention:'.video-mention',embed:'.content-block iframe',bookmark:'.video-bookmark'}[mode];await expect(page.locator(selector)).toBeVisible()}
 await page.locator('#save-draft').click();await expect(page.locator('#save-draft')).toBeDisabled();await page.locator('#preview-post').click();await expect(page.locator('#preview-body .video-bookmark')).toBeVisible();await page.locator('#close-preview').click();
 await page.screenshot({path:'/tmp/buiing-block-editor.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.setViewportSize({width:1200,height:950});
 await page.locator('#publish-post').click();await expect(page.locator('#publish-result')).toContainText('게시가 완료');assert.equal(uploads,1);assert.deepEqual(published[0].post.blocks.map(b=>b.type),['paragraph','image','youtube','paragraph']);assert.ok(published[0].post.blocks[1].src.startsWith('https://test.supabase.co/storage/'));assert.equal(published[0].post.blocks[2].mode,'bookmark');
 await page.goto(base+'write/?edit=react-thinking');await expect(page.locator('#edit-title')).toHaveValue('원래 글');await page.locator('#edit-title').fill('수정된 제목');await page.locator('#publish-post').click();await expect(page.locator('#publish-result')).toContainText('게시가 완료');assert.equal(published.at(-1).sha,'old-sha');assert.equal(published.at(-1).post.id,'react-thinking');
 // Setup/network failure must retain the draft and never report success.
 await page.locator('#new-post').click();await page.locator('#edit-title').fill('실패해도 남는 초안');await page.locator('[data-text="0"]').fill('보관');await page.locator('#save-draft').click();await expect(page.locator('#save-draft')).toBeDisabled();fail=true;await page.locator('#publish-post').click();await expect(page.locator('#editor-status')).toContainText('게시 연결 설정');await expect(page.locator('#publish-result')).not.toContainText('게시가 완료');fail=false;
 await page.locator('#draft-panel summary').click();const before=await page.locator('[data-load]').count();page.on('dialog',d=>d.accept());await page.locator('.draft-item').filter({hasText:'실패해도 남는 초안'}).locator('[data-delete-draft]').click();await expect(page.locator('[data-load]')).toHaveCount(before-1);await expect(page.locator('#edit-title')).toHaveValue('');await expect(page.locator('#save-draft')).toBeDisabled();
 admin=false;await page.goto(base+'write/');await expect(page.locator('#write-content')).toContainText('운영자 전용');assert.equal(await page.locator('#editor').count(),0);assert.deepEqual(errors,[]);console.log('Editor UI passed: dirty tracking, multiple drafts, manual/periodic autosave, deletion, inline image drop, 4 YouTube modes, preview, publish/edit, failure recovery, mobile and admin gating.');
}finally{await browser.close()}
