import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('Anonymous comments are read-only; secrets, service RPCs, context boundaries, filters, deletion and votes are enforced',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email_confirmed_at timestamptz,raw_user_meta_data jsonb);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated;`);await db.exec(await readFile('supabase/schema.sql','utf8'));const migration=await readFile('supabase/guest-community.sql','utf8');await db.exec(migration);await db.exec(migration);
 const actor='a'.repeat(64),salt='b'.repeat(32),hash='c'.repeat(64);
 const create=async({scope='guestbook',slug=null,thread=null,parent=null,name='Guest',body="<script>alert(1)</script>'; DROP TABLE entries; --",actorId=actor}={})=>(await db.query('select public.secure_guest_create($1,$2,$3::uuid,$4::uuid,$5,$6,$7,$8,$9) as id',[scope,slug,thread,parent,name,body,salt,hash,actorId])).rows[0].id;
 await db.exec('set role service_role');const root=await create();const child=await create({parent:root,body:'reply'});const second=await create({parent:child,name:'Second',body:'reply to reply'});await assert.rejects(()=>create({scope:'comment',slug:'other-blog',parent:root}),/INVALID_PARENT/);
 await assert.rejects(()=>create({scope:'thread',thread:'00000000-0000-4000-8000-000000000010'}),/THREAD_NOT_FOUND/);await assert.rejects(()=>create({name:'x'.repeat(41)}),/INVALID_CONTENT/);await assert.rejects(()=>create({body:'x'.repeat(10001)}),/INVALID_CONTENT/);
 assert.equal((await db.query('select public.secure_guest_vote($1,$2) as result',[root,actor])).rows[0].result.likes,1);assert.equal((await db.query('select public.secure_guest_vote($1,$2) as result',[root,actor])).rows[0].result.already,true);
 assert.equal((await db.query('select public.secure_guest_delete($1,$2,false) as deleted',[root,'wrong'])).rows[0].deleted,false);assert.equal((await db.query('select public.secure_guest_delete($1,$2,null) as deleted',[root,'wrong'])).rows[0].deleted,false);
 await db.exec('reset role;set role anon');const visible=(await db.query('select * from public.guest_entries')).rows;assert.equal(visible.length,3);assert.match(visible.find(e=>e.id===root).body,/DROP TABLE/);assert.equal(visible.find(e=>e.id===second).parent_id,root);assert.equal(visible.find(e=>e.id===second).reply_to_name,'Guest');assert.ok(!JSON.stringify(visible).includes(hash));
 for(const sql of ['select * from private.guest_credentials','select * from private.guest_votes',`select public.secure_guest_secret('${root}')`,`select public.secure_guest_delete('${root}',null,true)`,`select public.secure_guest_vote('${root}','${actor}')`,`insert into public.guest_entries(id,scope,root_id,author_name,body) values(gen_random_uuid(),'guestbook','${root}','x','attack')`,`update public.guest_entries set likes=999 where id='${root}'`])await assert.rejects(()=>db.exec(sql),/permission denied/);
 await db.exec('reset role;set role authenticated');await assert.rejects(()=>db.exec(`select public.secure_guest_secret('${root}')`),/permission denied/);await db.exec('reset role');await db.exec("update private.settings set blocked_words=array['BAD'],filter_mode='reject'");await db.exec('set role service_role');await assert.rejects(()=>create({name:'bAd'}),/BLOCKED_WORD/);await assert.rejects(()=>create({body:'this is BAD'}),/BLOCKED_WORD/);await db.exec("reset role;update private.settings set filter_mode='mask';set role service_role");const masked=await create({name:'BAD',body:'Bad test'});await db.exec('reset role');assert.equal((await db.query('select author_name,body from public.guest_entries where id=$1',[masked])).rows[0].body,'＊＊＊ test');
 await db.exec('set role service_role');assert.equal((await db.query('select public.secure_guest_budget($1,$2) as allowed',[actor,'create'])).rows[0].allowed,true);assert.equal((await db.query('select public.secure_guest_budget($1,$2) as allowed',[actor,'create'])).rows[0].allowed,false);assert.equal((await db.query('select public.secure_guest_budget($1,$2) as allowed',[actor,'create'])).rows[0].allowed,false);
 await db.query('select public.secure_guest_ban($1)',[masked]);await assert.rejects(()=>create(),/ACCOUNT_BANNED/);await assert.rejects(()=>db.query('select public.secure_guest_vote($1,$2)',[root,actor]),/ACCOUNT_BANNED/);
 await db.query('select public.secure_guest_unban($1)',[masked]);await create({body:'Unbanned'});assert.equal((await db.query('select public.secure_guest_delete($1,$2,false) as deleted',[root,hash])).rows[0].deleted,true);await db.exec('reset role;set role anon');assert.equal((await db.query('select * from public.guest_entries where root_id=$1',[root])).rows.length,0);
 // Guest data attached to a withdrawn/private article is hidden by RLS as well as the UI.
 await db.exec('reset role;create table public.published_posts(id text primary key,post jsonb);');await db.exec('set role service_role');const articleComment=await create({scope:'comment',slug:'public-article',actorId:'d'.repeat(64),body:'was public'});await db.exec('reset role');await db.query('insert into public.published_posts values($1,$2::jsonb)',['public-article',JSON.stringify({visibility:'withdrawn'})]);await db.exec('set role anon');assert.equal((await db.query('select * from public.guest_entries where id=$1',[articleComment])).rows.length,0);await db.exec('reset role;set role service_role');await assert.rejects(()=>create({scope:'comment',slug:'public-article',actorId:'d'.repeat(64)}),/POST_PRIVATE/);await assert.rejects(()=>db.query('select public.secure_guest_vote($1,$2)',[articleComment,'e'.repeat(64)]),/ENTRY_NOT_FOUND/);
 }finally{await db.close()}
});
