import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {transformSync} from 'esbuild';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
const source=transformSync(await readFile('supabase/functions/guest-interactions/index.ts','utf8'),{loader:'ts'}).code;
function service({budget=true,admin=false,signedIn=true}={}){let handler,stored,calls=[];const fetch=async(url,opts)=>{let body;try{body=JSON.parse(opts.body||'{}')}catch{};calls.push({url,body,headers:opts.headers});if(url.endsWith('/auth/v1/user'))return Response.json({id:'owner'},{status:signedIn?200:401});if(url.endsWith('/rpc/is_admin'))return Response.json(admin);if(url.endsWith('/rpc/secure_guest_budget'))return Response.json(budget);if(url.endsWith('/rpc/secure_guest_create')){stored=body;return Response.json('00000000-0000-4000-8000-000000000001')}if(url.endsWith('/rpc/secure_guest_secret'))return Response.json(stored?{salt:stored.p_salt,hash:stored.p_hash}:null);if(url.endsWith('/rpc/secure_guest_delete'))return Response.json(true);if(url.endsWith('/rpc/secure_guest_vote'))return Response.json({likes:1,already:false});if((url.endsWith('/rpc/secure_guest_ban')||url.endsWith('/rpc/secure_guest_unban')))return Response.json(true);throw Error('Unexpected fetch')};vm.runInNewContext(source,{Deno:{env:{get:k=>({SUPABASE_URL:'https://project.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'secret-service-key',SUPABASE_ANON_KEY:'anon-public-key'})[k]},serve:h=>handler=h},fetch,crypto:webcrypto,TextEncoder,TextDecoder,Uint8Array,Request,Response,URL});return {call:(input,headers={})=>handler(new Request('https://project.supabase.co/functions/v1/guest-interactions',{method:'POST',headers:{origin:'https://rihoyo.github.io','content-type':'application/json','x-forwarded-for':'203.0.113.10',...headers},body:typeof input==='string'?input:JSON.stringify(input)})),get stored(){return stored},get calls(){return calls}}}
const create={action:'create',scope:'guestbook',name:'Guest',password:'private-pass',body:"<script>alert('x')</script>; DROP TABLE guest_entries; --"};
test('Guest gateway salts password hashes, hides network data and verifies delete passwords without login',async()=>{const s=service();const created=await s.call(create);assert.equal(created.status,200);assert.equal((await created.json()).id,'00000000-0000-4000-8000-000000000001');assert.equal(s.stored.p_name,'Guest');assert.equal(s.stored.p_body,create.body);assert.match(s.stored.p_salt,/^[a-f0-9]{32}$/);assert.match(s.stored.p_hash,/^[a-f0-9]{64}$/);assert.match(s.stored.p_actor,/^[a-f0-9]{64}$/);assert.ok(!JSON.stringify(s.calls).includes('private-pass'));assert.ok(!JSON.stringify(s.calls).includes('203.0.113.10'));const other=service();await other.call(create);assert.notEqual(s.stored.p_salt,other.stored.p_salt);assert.notEqual(s.stored.p_hash,other.stored.p_hash);const id='00000000-0000-4000-8000-000000000001';assert.equal((await s.call({action:'delete',id,password:'incorrect'})).status,403);assert.ok(!s.calls.some(c=>c.url.endsWith('/secure_guest_delete')));assert.equal((await s.call({action:'delete',id,password:create.password})).status,200);assert.equal(s.calls.at(-1).body.p_admin,false)});
test('Guest gateway blocks cross-origin, malformed, oversized, honeypot and rate-limited requests before hashing or writes',async()=>{for(const [body,headers,status] of [[create,{origin:'https://evil.example'},403],[create,{'content-type':'text/plain'},400],['{bad',{},400],[{...create,body:'x'.repeat(70000)}, {},413],[{...create,password:'x'}, {},400],[{...create,parent:'bad'}, {},400],[{...create,website:'bot'}, {},400]]){const s=service();assert.equal((await s.call(body,headers)).status,status);assert.equal(s.calls.length,0)}const limited=service({budget:false});assert.equal((await limited.call(create)).status,429);assert.equal(limited.calls.length,1);assert.equal(limited.stored,undefined)});
test('Guest moderator deletion and banning require server-verified Auth and administrator role',async()=>{const id='00000000-0000-4000-8000-000000000001';for(const options of [{admin:false},{admin:true,signedIn:false}]){const s=service(options);assert.equal((await s.call({action:'admin-delete',id},{authorization:'Bearer fake-user'})).status,403);assert.ok(!s.calls.some(c=>c.url.endsWith('/secure_guest_delete')))}const admin=service({admin:true});assert.equal((await admin.call({action:'admin-delete',id},{authorization:'Bearer owner'})).status,200);assert.equal(admin.calls.at(-1).body.p_admin,true);assert.equal((await admin.call({action:'admin-ban',id},{authorization:'Bearer owner'})).status,200);assert.equal((await admin.call({action:'admin-unban',id},{authorization:'Bearer owner'})).status,200)});
